### ISSUE TITLE
cancelation month not correctly checked

### ISSUE THREAD

**Issue by motu55** [juntagrico/juntagrico#101]
here
https://github.com/juntagrico/juntagrico/blob/4141dd2446863e870a50d3002c71fd660204f087/juntagrico/views_subscription.py#L141

and probably somewhere else the cancelation mont is not corectly checked
it should be if the date is between last day in cancelation month and the start of the new business year nothing should hapen otherwise change the date

put this into the temporal util file

**Comment by SchroederB** [comment]
The solutionb to this problem is in branch:
[https://github.com/juntagrico/juntagrico/tree/cancellation_month_check](cancellation_month_check_branch)

**Comment by pascalfree** [comment]
I can't see a commit on this branch. Did you push your changes?

**Comment by motu55** [comment]
also create a pull request so that we can review it

**Comment by wknds** [comment]
done
