### ISSUE TITLE
Allow admins to update member details without enforcement of non-empty phone number field

### ISSUE THREAD

**Issue by nixnuex** [juntagrico/juntagrico#106]
Request from an ooo admin user: For some old members, there is no phone number in the required phone number field. Administrators should be able to change a member‘s mail address without having to type in an (invalid) phone number in case of a previously empty phone number field as enforced by the admin panel.

**Comment by motu55** [comment]
Usually email adresses are changed by user request. So there is a communication channel to the user and its possible to ask for the phonenumber if it is missing.
The question is, if there is a valid reason to change the email of a member without that it was requested by said member? (Or if there are people with an email adress but no phonenumber, but i cannot imagine this use case)

**Comment by motu55** [comment]
Git feedback on different chanel. As expected the user can be asked for a valid phonenumber
so this issue is invalid
