### ISSUE TITLE
Calculation of required shares for subscriptions with multiple members

### ISSUE THREAD

**Issue by nixnuex** [juntagrico/juntagrico#114]
Situation:
Member A has a subscription (2 required shares) with 2 paid shares (Anteilsscheine).
Member B joins the organization (1 paid share) and then the subscription of Member A. They now share one single subscription.

Expected result: The check for number of shares per subscription should be calculated based on all participant's shares.
Actual outcome: Member B sees the request after login to purchase another share (to reach 2 paid shares) because of the subscription requiring 2 shares.

This is what I experienced a couple of weeks ago. Could you please check?

**Comment by motu55** [comment]
I cannot reproduce this behavior
are you sure your are not confusing it with the unpaid shares message?

**Comment by nixnuex** [comment]
You are right. Tried to reproduce but only found the "unpaid shares" message.
