### ISSUE TITLE
Warning: DateTimeField Job.time received a naive datetime while time zone support is active

### ISSUE THREAD

**Issue by nixnuex** [juntagrico/juntagrico#122]
Warning in log:
`/usr/local/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1423: RuntimeWarning: DateTimeField Job.time received a naive datetime (2019-11-12 00:00:00) while time zone support is active.
  RuntimeWarning)`

**Comment by nixnuex** [comment]
This issue still persists. Should be reopened to investigate.

**Comment by motu55** [comment]
found some places and fixed them if more occur please let us know
