### ISSUE TITLE
Improve Customizability of Templates

### ISSUE THREAD

**Issue by puraverdura** [juntagrico/juntagrico#125]
Sometimes it would be nice to change the text on a web page view to clarify certain points and to have a bit more creative freedom in the wording in general.
Is it possible to have a similar template system as for the e-mails, but for the texts on the website? So that I can specify in the settings which template I want to use for which page?

That way the templates don't have to fit for everyone, which might make the development process also easier?

**Comment by motu55** [comment]
Basically django allows to overload templates so there is no need to implement that again.
Also do the webtemplates contain way more complex logic than the mailtemplates. 
If texts are unclear  changes can be proposed

**Comment by pascalfree** [comment]
Maintainability of overridden templates could be improved by putting the larger text parts into blocks and using this template loader:

**Comment by motu55** [comment]
this example is more for extending than replacing so we would not need a specific template loader but would need to but the texts into blocks.
but then again we do not have a lot of large textblocks
anyway i will close this again and while we can put the "larger" texts into blocks but i would like to do that on a need to do basis like with the hooks.
so if somebody needs a text in a block open an issue and we can have a look at this
