### ISSUE TITLE
Make job types archivable

### ISSUE THREAD

**Issue by pascalfree** [juntagrico/juntagrico#141]
Old job types can/should not be deleted as assignments depend on them.
The admin view of job types gets cluttered with types that are not used anymore.

Suggestion: create an "archived" flag on the job type, that:
* can be filtered out in the admin view
* takes the job type out from the drop-down when creating/editing a job.

**Comment by motu55** [comment]
basically that can be achieved by converting a jobtype into onetime jobs. the advantage of this approach is, that the jobtype is deleted and the assignments are still there until they are deleted as well.
the disadvantage is, if you want to de-archive you can convert one of the onetime jobs back to a jobtype.
while this perfectly does the archiving it is probably not that intuitive to do it that way. so if the functionality which is already there is not enough there ar two options what we can do:
-option1: add the convert to onetime job function again under the label "archive"
- option2: add a flag called visible (to use the same term everywhere) and let it affect the dropdown
the drawback of option2 is that after the archiving one has still to do a cleanup of the archived jop types.

**Comment by pascalfree** [comment]
I agree with option 2.
Option 1 would clutter the one time jobs instead.

Is there a proper cleanup procedure yet? That's another point that should probably be addressed.
