### ISSUE TITLE
Make subscription related URLs independent of id

### ISSUE THREAD

**Issue by pascalfree** [juntagrico/juntagrico#142]
Most pages regarding subscriptions contain its id e.g.
`/my/subscription/change/overview/42/`
This makes it impossible to send out a direct link that is valid for all members e.g. to point them directly to where they can change a certain setting.

The id is used to differentiate between the user's current and future subscription.

I suggest to make the ID optional. If no ID is given the page should default to the user's current subscription.

In addition the future subscription could be referred to by adding a neutral `/future` to the url.

This would be backwards compatible i.e. the old URLs with the IDs would still work.

**Comment by motu55** [comment]
Unfortunatelly django has no easy way to make parameters optional. Either we have to add all the urls again or we have to use non capturing groups in regular expression where it is not clear if reverse still works. 
No mather which way we go the code becomes less readable and maintainable, non to speak to duplicate all tests.
So even if someone would make all the effort to implement this we would not put it in the core code.
Also we have an url for the subscription Overview without an id. 
So you would have to use this and then the > notation to describe where to click to navigate, as every other tool does.
