### ISSUE TITLE
Add Job management for Administrators

### ISSUE THREAD

**Issue by motu55** [juntagrico/juntagrico#163]
A new drop dowm menu item should be added called
"Einsatz Management"
there are two sub entries

- Arbeitsteinsätze: Containing some statistics about assingments (date range, amount) and the possibility to delete all older than a certain date passed through a form. only visible to super admins and operation group
- JobArten: An instance of a management list showing either all types if the user is admin or operation group or only the relvant ones if a user is coordinator. the list should have the following columns:
Name (filterable) also a link back to the admin form of this instance
Tätikeitsbereich (filterable)
Anzahl Arbeitseinsätzt (fiterable)
Zuletzt benutzt(non filterable)
Sichtbar (non filterable) slider to toggle visiility
Löschen (non filterable, no title) button to delete type  only enabled if no assignements are around
This table should be visible to super admin operation group and coordinators

**Comment by pascalfree** [comment]
Regarding statistic for the assignments check this out:
https://github.com/mehalsgmues/juntagrico-mag/blob/master/mehalsgmues/views/stats.py#L26-L47
In general regarding assignments I think #352 is covering what is relevant there.
For the cleanup rather the jobs should be considered directly. #518 could solve this. i.e. in the admin have a filter to show jobs older than x to filter them easily.

For the job types it's probably also easier to add another model admin for that. i.e. create a proxy model of the jobtypes. Access can be limited with the default permissions. Deletion can be done by selection and admin actions. For the last used field annotations shall be used for better performance.

**Comment by pascalfree** [comment]
The table for job types is partially implemented by #675. Except for the assignment count and the delete option.

**Comment by pascalfree** [comment]
The key elements of the issue have been implemented with the mentioned PRs.
For the use case of cleaning up unused job types, follow up on #540
