### ISSUE TITLE
Typical mail template should be covered by unit test

### ISSUE THREAD

**Issue by nixnuex** [juntagrico/juntagrico#170]
A typical mail template code for upcoming jobs with open slots looks like:

	import datetime
	from juntagrico.entity.jobs import Job
	days_ahead = 6 - timezone.now().weekday()
	if days_ahead <= 0: 
	    days_ahead += 7
	start_sunday = timezone.now() + datetime.timedelta(days_ahead)
	days_ahead += 7
	end_sunday = timezone.now() + datetime.timedelta(days_ahead)
	jobs = Job.objects.filter(time__gte=start_sunday, time__lte=end_sunday).order_by("time")
	weekdays=[]
	for job in jobs:
	    if job.free_slots > 0:
	        if len(weekdays)>0 and job.weekday_name() == weekdays[-1]['name']:
	            weekdays[ -1 ]['jobs'].append(job)
	        else:
	            day={}
	            day['name'] =  job.weekday_name()
	            day['jobs'] = [job]
	            weekdays.append(day)
	renderdict.update({
	'weekdays': weekdays
	})

This is read from DB and parsed by `exec()` and should thus be covered by a new unit test in case some of the underlying objects change.

**Comment by wknds** [comment]
I could do this..

**Comment by motu55** [comment]
issues not labeled ready for implementation do first need some consideration so wait with implementing this

**Comment by motu55** [comment]
templates should be tested by the solawis themselves
this way theay are also documented somewhere if the db crashes
