### ISSUE TITLE
Job site not required stuff

### ISSUE THREAD

**Issue by etteru** [juntagrico/juntagrico#180]
The links on job participants currently all point to /my/jobs/<job_id>/#. 

![image](https://user-images.githubusercontent.com/7338220/75481247-095f4000-59a3-11ea-840c-71f4d362894e.png)

This makes no sense. The link should be removed:

![image](https://user-images.githubusercontent.com/7338220/75481353-34e22a80-59a3-11ea-9513-9ea44cfe76d8.png)

**Comment by motu55** [comment]
this seems to be some legacy code it can be removed alongside the comment part
https://github.com/juntagrico/juntagrico/blob/master/juntagrico/templates/job.html#L159

**Comment by etteru** [comment]
[Done](https://github.com/juntagrico/juntagrico/pull/181/commits/fe20ec19b364970604e7132cb173a0e7d6e28cdc). Thanks for the review!
