### ISSUE TITLE
Auf den Depotlisten "Tasche retour" gegen "Kiste retour" ersetzen

### ISSUE THREAD

**Issue by jolling-eg** [juntagrico/juntagrico#184]

**Comment by motu55** [comment]
we have to check if we want to add the tasche to the vocabulary or if we try to find a generic word like "Gebinde"

**Comment by nixnuex** [comment]
Looks like this wording might be strongly linked to the identity of the cooperative. I would recommend to let them choose individually through the vocabulary.

**Comment by motu55** [comment]
since we would not find a word i guess we have to add it to the vocabulary
