### ISSUE TITLE
Deactivation of subs that have a deactivation date fails

### ISSUE THREAD

**Issue by pascalfree** [juntagrico/juntagrico#188]
This condition also triggers, if one tries to deactivate a subscription (back or frontend) that already has a deactivation date (but still have activate ticked). Should only trigger, when `instance.active is True`.
https://github.com/juntagrico/juntagrico/blob/28b82c624bee13806185876e0a0ab8e1a9597806/juntagrico/lifecycle/sub.py#L55
When deactivating via frontend (cancellation list) this causes a 500 server error.

The solution is easy, but may be obsolete with the planned refactor that removes the active boolean.
Just opened the issue to keep that case in mind, when refactoring.

**Comment by motu55** [comment]
this has become obsoltete with the refactor

**Comment by dgl-cw** [comment]
https://github.com/juntagrico/juntagrico/pull/204

**Comment by pascalfree** [comment]
https://github.com/juntagrico/juntagrico/pull/204
