### ISSUE TITLE
Event countdown (timer) is lagging.

### ISSUE THREAD

**Issue by wknds** [juntagrico/juntagrico#189]
The countdown on the event page does not go along with the period between the time now and the time of the upcoming event.

![Screenshot_20200323-084033](https://user-images.githubusercontent.com/25268078/77333516-72747200-6d1b-11ea-9a37-d08381db731f.png)

**Comment by pascalfree** [comment]
This is most likely just an issue on our instance, as our time zone is not set correctly yet. Can you reproduce that in your local test environment?

**Comment by wknds** [comment]
It might be, i am going to test this on my local system (y)

**Comment by motu55** [comment]
could not reproduce on my.ortoloco, so this seems an insatnece config problem

**Comment by pascalfree** [comment]
@wknds I fixed this recently in our instance if you want to confirm that.

**Comment by wknds** [comment]
The countdown is correct now in our instance!
