### ISSUE TITLE
Limit mail FROM: to single allowed domain

### ISSUE THREAD

**Issue by nixnuex** [juntagrico/juntagrico#191]
Currently, juntagrico allows sending e-mails with arbitrary `FROM:` addresses when using e.g. the mailer form as a Tätigkeitsbereichsleiter which is set up with a personal mail address. This is an issue with spam prevention techniques of modern receiving mail providers (especially SPF & DKIM). All mails sent from juntagrico should have a single originating `FROM:` domain which can then be configured for best practice.

For user-to-user mails through juntagrico, this is already solved by sending from `Config.info_email()` with a `REPLY-TO:` header containing the sending user's mail address.

I would suggest to filter outgoing mail for allowed `FROM:` domains and replace `FROM:` and add `REPLY-TO:` in case needed. The valid domain could either become a new config parameter or be extracted from the `Config.info_email()`.

**Comment by motu55** [comment]
see here
https://github.com/juntagrico/juntagrico/blob/a296f8745fd37d9f5404f4858d5c417757a5edbe/juntagrico/mailer.py#L55
https://github.com/juntagrico/juntagrico/blob/a296f8745fd37d9f5404f4858d5c417757a5edbe/juntagrico/mailer.py#L24
https://github.com/juntagrico/juntagrico/blob/a296f8745fd37d9f5404f4858d5c417757a5edbe/juntagrico/mailer.py#L27

we do that allready for the contact forms so we would only need to identify the places where we missed it.

a general mechanism could be devised but i would not use a config value rather use the domain from the info email, 
or use the email specified for sending and allways use the reply to field if it is not the same(would be the safest)

So we have the 3 possible solutions:
1) adapt the code at the point missing the check
2) add a general mechanism here https://github.com/juntagrico/juntagrico/blob/a296f8745fd37d9f5404f4858d5c417757a5edbe/juntagrico/mailer.py#L21
2.1) use the domain of the configured info email assuming it is ok to send from other emails in the same domain
2.2) use the email adress configured for the smtp (if it is an email adress) and if not the same use the reply to. this would also cover the services where sending from the same domain is not allowed

**Comment by pascalfree** [comment]
I think 2.2 is the most stable solution.
I'm working on the E-mail sender for another pull request right now, please wait with the implementation of this one.

**Comment by nixnuex** [comment]
I would prefer to still allow variable sender addresses from the main domain. The reply-to is just a work-around. Voting for 2.1 based on the smtp login domain (if set) or the info domain (fallback).

**Comment by pascalfree** [comment]
I'm fine with 2.1 too.
The email sender refractor is done and this can be implemented.

**Comment by motu55** [comment]
since we get cooperative who would like to use a gmail email adress for sending email, version 2.1 would not work anymore.
and let's not forget email senders can be changed with the settings
so the idea here is to add more mailers like this
https://github.com/juntagrico/juntagrico/blob/master/juntagrico/util/defaultmailer.py
one for 2.2 and one for 2.1 
also move the default mailer and the new mailers into a module inside 
https://github.com/juntagrico/juntagrico/tree/master/juntagrico/mailer
and adapt the documentation accordingly

**Comment by nixnuex** [comment]
To me it seems like limiting the `FROM:` of the outgoing mails is largely independent of the consecutive `mailer` and might be good to be kept under control by a "gatekeeper" early-on.

What about a new config value `EMAIL_ALLOWED_FROM` with possible values
- `info_address` (`FROM:` is always info mail address, `REPLY-TO:` contains internal "sender")
- `info_domain` [default] (`FROM:` is allowed for full domain, closest to current behavior)

that allows an easy, flexible filter?

**Comment by motu55** [comment]
out of laziness I found quite a good solutions since it alows for avariety of solution for avariety of problems
https://xkcd.com/208/
