### ISSUE TITLE
Make permissions more granular

### ISSUE THREAD

**Issue by nixnuex** [juntagrico/juntagrico#199]
Some permissions (e.g. depot list download) are linked or at least named to a group level (e.g. `juntagrico.is_operations_group`). This should be made more granular to attribute access in details even to individual members.

**Comment by PaulKC** [comment]
We would also like to have a more granular way to control which links are shown. Would it be possible to link the visibility to the permissions a user has? For example it makes no sense to display the 'Anteilscheine Kündigungsliste' if the user can not view the Anteilscheine.

**Comment by motu55** [comment]
I would not use the django default  permissions for detecting whcih links a user can see. but create a permission for each link on the first level so a permission for the abo management but not one for each sub link there
