### ISSUE TITLE
Make area and depot admin permissions implicit

### ISSUE THREAD

**Issue by pascalfree** [juntagrico/juntagrico#200]
Currently the permissions `is_area_admin` and `is_depot_admin` have to be given to the respective members in addition to making them coordinators of an area or depot. This could be combined in 2 ways:

1. Set the coordinators permissions in pre_save when saving a depot or activity area.
2. Make a custom decorator to check access to the view like `@area_admin_required` that replaces `@permission_required('juntagrico.is_area_admin')`. There are other locations where this permission is currently used and could be replaced similarly.

**Comment by pascalfree** [comment]
Having a deeper look at this.
If the coordinator should also have access to the django-admin, additional permissions must be set. This is fine, as different organisations may give different responsibilities to their coordinators.

As permissions must be set anyways (in most cases) the original issue is less relevant. However it should be documented, that these features for the area and depot coordinators exist and how they can be set up.

**Comment by motu55** [comment]
marked it as a documentation issue, so no code need but some explaining in the docs
