### ISSUE TITLE
Membership and Share Management (for Members)

### ISSUE THREAD

**Issue by pascalfree** [juntagrico/juntagrico#201]
Here are some suggestions, regarding how the members could see and manage their membership status:

- [ ] Membership page: Replace `Personalien` in menu with `Mitgliedschaft`.
- [x] List own shares on the membership page including status and a link to order new shares or cancel them.
- [ ] Only _display_ personal information on main membership page and add button that leads to a form to edit the information
- [x] Show Membership status. E.g Member since, active/cancelled

The changes are also meant to give the members a clearer intuitive understanding, that their subscription can be cancelled/added independently of the their membership.

**Comment by motu55** [comment]
the replacement text for Personalien should be dicussed.
i do not think an extra form page is required. showing your stuff in a form is pretty much a standard thing in webapps.
the shares list is a good idea (but still would leave the info also on the subscription page)
also the state of the meberships is a good point. please create two separate issues for these

**Comment by motu55** [comment]
see #246 #247
