### ISSUE TITLE
Allow the user to define a nickname

### ISSUE THREAD

**Issue by PaulKC** [juntagrico/juntagrico#207]
Some members do not want to use their real name on the lists or WGs would like to use a nickname.

**Comment by pascalfree** [comment]
We had some similar issue recently.
Some of our WGs are legal associations registered as a "legal person" that have their own shares and thus can be primary member of a subscription. In this case their "Verein" is added as a member (abusing first and last name fields) in Juntagrico. As a result that name shows up in the depotlist. That is the "easy" case. 

For other cases this won't work. For WGs (that are not a legal person) it is actually the subscription (that they share) that should be named (and then be displayed as such on the depotlist) 

So far we had no requests of individual members that didn't want to have their real names displayed. But it is their right I guess.
I would not give the members direct access to set a nickname themselves (just via Django admin on request). If you need that, there should be a setting to disable it imo.

**Comment by motu55** [comment]
what would be the benefit of user not being able to define a nickname?

**Comment by pascalfree** [comment]
Easier for user management, a more professional look or a stronger identification as a community.
Basically: I would want to disable it.

I'm in for naming subscriptions with more than 1 person though. 😉

**Comment by motu55** [comment]
It should be done like this
Add a new field for the nickname inside the subscription entity
Show this information in the subscription page only if the value is set other do not show that no value is present
thr value can be set trough a form which is accessed through the change subscription page
the value is displayed in the depot lis in the "mitabonnenten" column 
the main member of a subscription should always be displayed
