### ISSUE TITLE
Make subscription types more readable for members

### ISSUE THREAD

**Issue by pascalfree** [juntagrico/juntagrico#209]
Currently subscription types have long names that contain partially irrelevant information like:
`Abotyp - Grösse: Normal - Produkt: Gemüse`
What parts of the name are actually relevant depends on how the subscription types are used.

The name could be customized, by turning this
https://github.com/juntagrico/juntagrico/blob/b65d40d3c55421ebde924ae528e1843bd6fbf318/juntagrico/entity/subtypes.py#L75-L76
into something like:
`subscription_name_format.format(name=self.name, size=self.size.name, product=self.size.product.name)`
where `subscription_name_format` could be defined in the settings.py and possibly be overwritten by the subscription type itself (in a model field).

**Comment by motu55** [comment]
the code you referenced is as far as i can see only visible in the admin backend?
if this is the case I do not see the problem if there is more information than needed, or am i missing something.
maybe it would be helpfull if you could make a concrete example where and how the display should be changed

**Comment by PaulKC** [comment]
This code is also used in the Subscription.get_size_name() method which is used to display the subscription overview of the member. I agree that this can be very confusing.

![image](https://user-images.githubusercontent.com/5611775/81299107-01441080-9076-11ea-837b-35c01b3ac313.png)

**Comment by motu55** [comment]
ok i see the point that should not be there
This string is only meant to be visible in the backend where it makes sense to have it this way 
So here the typename is not nescessary and the sizes should be grouped by product something like this:
Gemüse:
- Gross : 2
- Klein : 1
Milch
- 8 Liter : 1
- 4 Liter : 1 
A Side note:
The original design idea behind the type name was to identify the price/assignements part
So for example one has
Wenig mitarbeit - Grosse: klein - Produkt:Gemüse
Viel mitarbeit - Grosse: klein - Produkt:Gemüse
So in your case where you reuse the size name would it not make more sense to use something like this
Standard - Grösse:4 Liter - Produkt:Milch

**Comment by pascalfree** [comment]
To complete that, the type should be shown as well as in our case it would be:
```
Gemüse:
- 1 EAT:
  - Gemüse Solidarisch: 1
  - Gemüse Standard: 1
  - Gemüse für Alle: 2
```
Same like in the order form. 

It would probably work for everybody if levels that have only 1 "sibling" would "collapse" i.e. not show. 
Then it would collapse to the type for us:
```
Gemüse Solidarisch: 1
Gemüse Standard: 1
Gemüse für Alle: 2
```

And to the size for @PaulKC 
```
4 Liter: 1
8 Liter: 2
```

If only 1 Product is offered if should be clear what it is.

**Comment by motu55** [comment]
as above but maybe use the abo type long name which can be empty if you do not want to show something fot the abo type
