### ISSUE TITLE
Feature Request: Switch for driving license in profile

### ISSUE THREAD

**Issue by puraverdura** [juntagrico/juntagrico#215]
It would be cool if there was a Switch that let members select if they have a driving license or not. This information could then be displayed in the filtered list and help coordinate jobs, where a driver is needed.

All that's needed would be a new `BooleanField` in the `Member` class in `
juntagrico/juntagrico/entity/member.py` called for example `has_driving_license`

With that the form `MemberProfileForm` in `
juntagrico/juntagrico/forms.py` could be updated to contain a Slider with the label: `Hast du einen Führerschein?`

What do you guys think? I could make a pull request for this.

**Comment by pascalfree** [comment]
I would generalize this feature.

This label could in theory be emulated, using an activity area "Members with driving license", that such members subscribe to. However that's not intuitive.
I would suggest adding a new entity `Abilities` or `Badges` with a many-to-many relationship to members.
The abilities may be self-declarable or not (that would be a setting on the ability).

Later we could extend this, to require certain abilities for certain jobs etc.

**Comment by motu55** [comment]
i would go even futher and create an addon for custom member fields
from there on we could alse create an addon for custom filter lists or reports

**Comment by pascalfree** [comment]
Would that be an addon template?  Dynamicly adding fields seems hard in Django.

**Comment by puraverdura** [comment]
I like the generalized version of this feature! It could also be used for a bit of gameification (badge for achieving a certain number of jobs, very active member of activity area, ...).

**Comment by pascalfree** [comment]
I implemented a very basic version of this here https://github.com/juntagrico/juntagrico-badges
So far badges can be defined and they may or may not be self-assignable, i.e. the members can get them if they want, which would cover this driver license use case.
There is also a management list to view members that have a certain badge and a link to send them an email.

This is the member view:
![grafik](https://user-images.githubusercontent.com/1621900/131261421-1cf2a236-9bb8-4c13-aac7-ded18b44bbc4.png)

I called the badges "Abzeichen" for now. I'm open for other suggestions.
I would like to move the discussion to https://github.com/juntagrico/juntagrico-badges . Please open an issue there if you see the need.

**Comment by pascalfree** [comment]
Closing it here. Please open an issue on the [add-on](https://github.com/juntagrico/juntagrico-badges) if more is needed.
