### ISSUE TITLE
prohibit replay of subscription creation

### ISSUE THREAD

**Issue by motu55** [juntagrico/juntagrico#216]
it's a bit tricka to reproduce and somewhat rare that this might happen
but if the client closes the connection to my/create/subscription/summary/ which leads to a http 499 and does this at leas once or several times until it comes to the redirect, a lot of subscriptions will be created.
I do not know if a lot of emails are generated as well (I guess not otherwise this would have been flagged a lot earlier but I will check this)
We need some sort of protection against such a replay "attack" 
i would suggest the follwing checks and actions (maibe some of them are already there then investigate why they did not catch the issue):
- if a member already has a future_subscription it should fail (especially if it is the primary member)
- clean the session after the creation or add a flag to the session that it was created and check once it is called

**Comment by pascalfree** [comment]
PR fixes this by cleaning the session as early as possible.
The future_subscription check should an will probably be done with #212
