### ISSUE TITLE
Static file namespacing

### ISSUE THREAD

**Issue by pascalfree** [juntagrico/juntagrico#228]
As mentioned in the [django docs (green box at the end)](https://docs.djangoproject.com/en/3.0/howto/static-files/#configuring-static-files), the static files should be namespaced by putting them in another folder with the app name.
That prevents conflicts with addons and the juntagrico instance itself.

**Comment by motu55** [comment]
we have to investigate that, i am not shure if it only applies to the django runserver or also to collect static which we use and our static files are served from nginx and not django in production
