### ISSUE TITLE
Extra sub can_cancel default

### ISSUE THREAD

**Issue by nixnuex** [juntagrico/juntagrico#237]
Is it intended that extra subs cannot be canceled as long as an appropriate `extrasubbillingperiod` has been set up?

https://github.com/juntagrico/juntagrico/blob/082dba10707922c52d0e0fcd066db3b710351960/juntagrico/entity/extrasubs.py#L64-L70

**Comment by motu55** [comment]
yes this should return true if not in a current billing period
