### ISSUE TITLE
Depot list: subscription type and size text overlapping

### ISSUE THREAD

**Issue by nixnuex** [juntagrico/juntagrico#240]
In the depot list, the subscription type and size often are too wide for the table column width and thus overlap with the neighboring text. This makes it hard to read the header of the table.

Maybe rotating the text by 90° would solve the issue?

<img width="600" alt="DepotListIssue" src="https://user-images.githubusercontent.com/2345318/90182544-6cf2f380-ddb2-11ea-852e-a440851b5b0f.png">

**Comment by motu55** [comment]
that is an ongoing problem
no solution at the moment is satisfying
the problem with the 90 degree solutuion ist that we loose rows and have to adapt the row break everytime a size changes
page orientation would be a solution but then again we have less rows and would need more pags per depot
i have to think about it

**Comment by nixnuex** [comment]
The main issue is the limited CSS support of `xhtml2pdf`. It does not allow us to break words or turn them by 90° as far as I can see.

However, while trying to find a way around, I found a solution to the ongoing issue of unpredictable table/row heights and page breaks. There is a convenient way to let `xhtml2pdf` deal with page breaks while repeating the table header on every page as desired. See #242. This might allow us to focus on the header row issue mentioned here.
