### ISSUE TITLE
Add protected depot access information

### ISSUE THREAD

**Issue by pascalfree** [juntagrico/juntagrico#263]
Add a field to store information about how a depot can be accessed including codes etc.
This information should not be in the description field, as that one is also displayed in the registration process.
Then show this information on the depot page "my/depot/{id}".

In addition the url my/depot should just forward to the depot that the member is actually assigned to, to make sharing of the link easier.

**Comment by pascalfree** [comment]
With the current implementation the members can easily access the information about the other depots by typing the url with a different id, e.g. `my/depot/2` instead of their actual depot `my/depot/1`

Assuming that members have no malicious intentions this is a minor issue, but still.

**Comment by motu55** [comment]
Rather tha forbidd a member to access the page just do not display the information.
It might be required some day that a Person can access the page with the general depot information like opening hours when ghey choose a depot or change a depot
