### ISSUE TITLE
Config switch to change share_created.txt to mention sum of shares

### ISSUE THREAD

**Issue by nixnuex** [juntagrico/juntagrico#278]
Add config to allow to switch the `share_created.txt` mail text after share creation to switch the text `Bitte überweise N Mal den Betrag von CHF 250 auf das folgende Konto:` to `Bitte überweise den Betrag von CHF 500 auf das folgende Konto:`

**Comment by motu55** [comment]
there a setting to change the mail texts so this can be done there
