### ISSUE TITLE
Extra sub parts do not get cancelation date set on main sub cancel

### ISSUE THREAD

**Issue by nixnuex** [juntagrico/juntagrico#283]

**Comment by motu55** [comment]
it should be set see here
https://github.com/juntagrico/juntagrico/blob/dc2ce7eef3541b6a178cf86682b284e30cf7b6b0/juntagrico/views_subscription.py#L360

**Comment by nixnuex** [comment]
Just tested again on my local instance: everything but the extra sub gets a cancelation date (only start date is 01.01.2020).
