### ISSUE TITLE
Subscription Recipients

### ISSUE THREAD

**Issue by pascalfree** [juntagrico/juntagrico#308]
A brief review of the subscription recipient related functionality and possible issues.

- The `Subscription.recipients_all` method changed behaviour here: https://github.com/juntagrico/juntagrico/commit/094aa06cc93e46a85b90158cbf93dd86eac5460d#diff-964fdeb65157adee6f026e3c5e1e390bcffec52163fe75cbe906e673f8fc8542R169-R170
   - Before it was: All recipients for the current state of the subscription.
   - Now it is: All recipients that ever were, still are, and will be in this sub.
- The `recipients` method also changed
   - from "All recipients of current state of the sub that are active members" (i.e. a subset of `recipients_all`)
   - to "All current and future recipients of this subscription".

Usage of the methods:

## A: `recipients_all`

1. Count all uncancelled shares of all recipients of a subscription (used to evaluate if members have enough shares for subscription parts): 
    1. Here all current and future recipients can be considered, when ordering new sub parts, though the ordered sub parts can then only be actived after the the future recipients joined if their shares are needed. 
    2. For cancelling shares future recipients could also be considered, however for actual deactivation of the shares the future recipients must join before if their shares are needed.
    3. Conclusion: Here the new `recipients` method would fit
2. Count all assignments of co members: This is a big tbd anyways. To keep the previous behaviour we would only count current and possibly future recipients (that would be `recipients` as well)

## B: `recipients`

1. Listing the names of the recipients on depot list and on subscription filter list: **Only the current recipients should be shown on the depot list and only recipients that match the subscription state should be shown on the filter**.
2. Counting all paid shares of a subscription (used for display on the waiting list): **fits new method**
3. Evaluation when activating a sub, if any of the recipients are still in another active sub: Only future recipients should be considered, however there can't be current recipients (as the sub was not active yet) so **new method works**. _Bug notice: Current implementation does not consider future activation dates of sub, e.g. if recipient leaves old subscription in the future but before new one is activated (also in the future), the check should pass, but it will raise an error._
4. Check if primary member is a recipient: **Here only recipients that match the subscription state should be allowed**.
5. People that are informed about a depot change of a subscription: **current and future are fine**.
6. Check when adding co-members, that new email is not used by any recipient already: **current and future are fine**, as theoretically past recipients could be re-added.
7. Showing other members of the own sub in the overview (via `co_members` that behaves the same): **current and future are fine**

## C: `other_recipients`

acts like `recipients` but excludes primary member

1. selection of other member to make new primary member: **Here only current recipients should be allowed**

For sure I missed something somewhere. Let's discuss.

**Comment by motu55** [comment]
wouldn't it make more sense to rewrite the recipient method to their old 
behaviour?

**Comment by pascalfree** [comment]
Yes in many cases that's necessary.
In some cases we have new possibilities now that I tried to evaluate above.

For example, before, all members of a subscription (together) were either future members of it (if sub wasn't active yet), current members (on active sub), or past members (sub deactivated). Now, the state the member has in the subscription (past, current, future) is decoupled from the state of the subscription to some extend (members come and go individually). This leads to new cases, that have to be thought through.
