### ISSUE TITLE
Deactivated users should not be able to reset their password

### ISSUE THREAD

**Issue by nixnuex** [juntagrico/juntagrico#318]
Deactivated users can trigger a password reset via mail but cannot log in afterwards. This is confusing. No password reset action should be possible for deactivated users.

**Comment by pascalfree** [comment]
We now use the official password reset mechanism.

There is the `set_unusable_password()` method on the user, that, when used, [would result in no password reset email being sent](set_unusable_password()).
However the deactivation is date-based and may be in the future, i.e. we can not `set_unusable_password()` when we set the deactivation date.
Also this approach would need kind of a migration where the method is applied to all deactivated members.

Another option might be to monkey patch the `is_active` flag of the user, [which is also checked in the password reset process](https://github.com/django/django/blob/8a7ac78b706797a03d26b88eddb9d1067ed35b66/django/contrib/auth/forms.py#L275), to match the deactivation status of the member.

Finally it may be the cleanest to just override the PasswordResetForm as [suggested here](https://github.com/django/django/blob/8a7ac78b706797a03d26b88eddb9d1067ed35b66/django/contrib/auth/forms.py#L268-L270) that would also allow us to [replace this patch](https://github.com/juntagrico/juntagrico/blob/a56ac0e913e579fae12fd4967bf00137c68c4e13/juntagrico/models.py#L79-L88).
