### ISSUE TITLE
Member share count in admin subscription should only count active shares

### ISSUE THREAD

**Issue by nixnuex** [juntagrico/juntagrico#331]
Currently, it shows the total amount of active and inactive shares. This is misleading for admin staff.

**Comment by motu55** [comment]
it should display the usable shares not the active shares

**Comment by nixnuex** [comment]
Currently, it does show the "usable" shares.

**Comment by motu55** [comment]
if you mean this
https://github.com/juntagrico/juntagrico/blob/master/juntagrico/entity/member.py#L84
the inactive shares are not counted

**Comment by motu55** [comment]
@nixnuex can you previde more context or an example to reproduce this issue?

**Comment by nixnuex** [comment]
My proposal was to only show active shares. But you want to show usable shares. The latter seems to be correctly implemented.

**Comment by motu55** [comment]
ok then this was a missunderstanding, inactive shares for me are cancelled and paid back shares.
usable shares are paid and unpaid shares
the idea behind this implementation is that an ordered but unpaid share will eventually become a paid share and we can use them for calculation if enough shares are present for a suscription. 
so the info shown in the subscription admin is the same info that is used to calculate if enough shares are present.
if these infos would be different it would be more confusing
