### ISSUE TITLE
Depot member filter shows unavailable send mails link in menu

### ISSUE THREAD

**Issue by nixnuex** [juntagrico/juntagrico#343]
The view set the bool `can_send_mails` which is usually linked to a permission. Would be better to replace it with new `show_send_mail_button` and modify the template case for the button on top of the list to include that new bool.

**Comment by motu55** [comment]
I do nit really get the issue could you please provide mor context or screenshots?

**Comment by nixnuex** [comment]
For Depot admins, this link should not be in the menu on the filter members view as it just leads to a login page (no permission).

![image](https://user-images.githubusercontent.com/2345318/104415665-afdc1180-5572-11eb-8aa3-392f6fd0bbc7.jpeg)

**Comment by motu55** [comment]
this seems to have dissapeared with the new admin menu

**Comment by nixnuex** [comment]
No, it's still the same.
