### ISSUE TITLE
Feature request (biocò): Simplified delivery entering

### ISSUE THREAD

**Issue by mbschenkel** [juntagrico/juntagrico#344]
## Background
biòco has now also migrated to the upstream Juntagrico (intranet.bioco.ch).
We are now trying to close some minor gaps to features that we had before on our custom version, and are missing now.
I could implement this myself, but would like your comments first.

Our subscription structure is quite simple: Half, full and double sizes.
And most of the time the same is shipped 2x per week.
In order to get the deliveries page right for everyone, we need to enter all 2x3 possible combinations.
So far we also had only one "Delivery" entry per delivery-day (mostly even per week).
We would like to reduce this effort from 6 to 2 or 1 entries.

![image](https://user-images.githubusercontent.com/6318378/104365999-07e62a00-5519-11eb-9f80-3bc9746318ba.png)

## Workaround
As a workaround I've currently added a second view, that calls
DeliveryDao.all_deliveries_order_by_delivery_date_desc()
instead of DeliveryDao.deliveries_by_subscription() (in juntagrico.views.deliveries)

![image](https://user-images.githubusercontent.com/6318378/104366330-7cb96400-5519-11eb-8c7f-ea397f9bad11.png)
(Note the duplicate menu entry "Lieferungen" and "Gemüsevorschau")

## Proposal
My implementation proposal is to 
a) add this alternative view (e.g. called juntagrico.views.all_deliveries) 
b) add a config option juntagrico.config.show_all_delivieries
   .. and document it in docs/settings.rst :-)
c) based on that pick the URL used in the menu to point to either the existing or the "all" view

An alternative could be to offer a nice way to overwrite the menu entries in the customization layer (without some ugly CSS / JS hacks).

## Risks
A risk I see is that the quantities would then be confusing for those not matching the 1 subscription size shown.
An easy way around would be not to show quantities at all...

FYI @herrnesto

**Comment by motu55** [comment]
See #348 for a better solution.
To fix your menu issue you can simply override the corresponding url see here
https://stackoverflow.com/questions/9306143/django-how-do-i-override-app-supplied-urls-in-my-project-urlconf

**Comment by mbschenkel** [comment]
@motu55 : Unfortunately the URL override does not work nicely if there are no deliveries matching the criteria of `deliveries_by_subscription` because they are hidden through the `show_deliveries` in `menu_dict`. So I would have to create dummy-delivery-entries for each subscription just to make the menu item visible...
