### ISSUE TITLE
Feature request (biocò): Support Mailtrap

### ISSUE THREAD

**Issue by mbschenkel** [juntagrico/juntagrico#345]
## Background

biòco has now also migrated to the upstream Juntagrico (intranet.bioco.ch).
We are now trying to close some minor gaps to features that we had before on our custom version, and are missing now.
I could implement this myself, but would like your comments first.

On a testing instance it would be nice to be able to see all e-mails that would be sent and still be in DEBUG=true mode.
We have used [mailtrap](mailtrap.io/) to catch them all without actually delivering to any recipients.
However with the current whitelisting structure, this seems impossible (except maybe if we would add *all* e-mails to the whitelist in bioco.settings)

## Proposal
My proposal would be to either split DEBUG mode and e-mail whitelisting by adding a new option  juntagrico.config.EMAIL_DEBUG (for backwards compatibility it could default to DEBUG) such that these 2 options are independent of each other

Alternatives could be to Interpret `settings.WHITELIST_EMAILS` entries as RegEx, callback function or to have some special value for `settings.WHITELIST_EMAILS` (e.g. "*") to change mode, but that does not seem very nice.

FYI @herrnesto

**Comment by herrnesto** [comment]
👍 to split debug mode and email whitelist in 2 different configurations.

**Comment by motu55** [comment]
went for the regex solution since it does not introduce a new super specialised setting most won't use and it is way more powerfull
