### ISSUE TITLE
Amount overview PDF does not appear to add up

### ISSUE THREAD

**Issue by mbschenkel** [juntagrico/juntagrico#347]
On my/pdf/amountoverview I get

![image](https://user-images.githubusercontent.com/6318378/104378679-a9c14300-5528-11eb-9723-fce6781f1e10.png)
But I would expect on Tuesday to see 6*0.5 + 29 + 2*2 = 36 not 33

Our subscription structure looks like this:
![image](https://user-images.githubusercontent.com/6318378/104378745-c3628a80-5528-11eb-8fbf-d01394654015.png)

FYI @herrnesto

**Comment by motu55** [comment]
We need to analyse this

**Comment by mbschenkel** [comment]
Good catch with the int-rounding... Thanks for the quick fix!

**Comment by mbschenkel** [comment]
For completeness:
works for us now
![image](https://user-images.githubusercontent.com/6318378/105099821-92480400-5aac-11eb-9704-98c5597b006b.png)
