### ISSUE TITLE
Can not add member to new subscription until old one is already left

### ISSUE THREAD

**Issue by pascalfree** [juntagrico/juntagrico#353]
## Use Case
When I have a member that wants to change to another subscription in the new year, I cancel the member's current subscription and enter her in the new one (without `join_date`). In the new subscription, however, I get the error that the member still has another active subscription, because only the `leave_date` is checked here
https://github.com/juntagrico/juntagrico/blob/1fd1520f147f53d6f176510c00e9ecd91ed1daf2/juntagrico/lifecycle/submembership.py#L59-L62

I would argue that if the old subscription is already _canceled_, it should be allowed to park the member in a new subscription.
Even if the previous subscription is not cancelled, the entry should be fine, if a (future) leave_date is set on the old subscription.

## Suggestion
Filter out cancelled subscriptions in this query: 
https://github.com/juntagrico/juntagrico/blob/1fd1520f147f53d6f176510c00e9ecd91ed1daf2/juntagrico/dao/subscriptionmembershipdao.py#L13-L16
And instead of checking that the `leave_date` has not passed (`~q_left_subscription()`), only look for empty `leave_date`s.

In addition I think there should be a check, that a new join_date (when set) is after the latest leave_date and all other leave_dates are set.

**Comment by nixnuex** [comment]
Related to #329?

**Comment by motu55** [comment]
nope it is a different problem
