### ISSUE TITLE
Inactive subscriptions shown on depot filter (my/filters/depot/N)

### ISSUE THREAD

**Issue by mbschenkel** [juntagrico/juntagrico#356]
Inactive subscriptions shown on depot filter (my/filters/depot/N).
Although such subscriptions can be filtered out (they appear with "kein Depot"), this can be misleading when a depot-admin is about to email the members in his depot, but also sends to past-members unintentionally.

![image](https://user-images.githubusercontent.com/6318378/105097124-6296fd00-5aa8-11eb-8fdd-cf239577bc5d.png)

**Side question:**
Is it intended that I need to manually assign the `juntagrico.is_depot_admin` permission to such users?
Wouldn't it be possible to have our own `@permission` that looks this up from the depot database table?

**Comment by nixnuex** [comment]
First part is duplicate of #349

**Comment by mbschenkel** [comment]
Uh, sorry didn't realize that.

**Comment by motu55** [comment]
duplicate of #349

**Comment by mbschenkel** [comment]
@motu55 / @nixnuex: What about the side-question above? (Should maybe be discussed on Slack, but I'm not on it yet)

_Is it intended that I need to manually assign the `juntagrico.is_depot_admin` permission to such users?
Wouldn't it be possible to have our own `@permission` that looks this up from the depot database table?_

**Comment by motu55** [comment]
that's the problem with packing more than one issue in an issue ;)
create a new issue

**Comment by pascalfree** [comment]
> @motu55 / @nixnuex: What about the side-question above? (Should maybe be discussed on Slack, but I'm not on it yet)
> 
> _Is it intended that I need to manually assign the `juntagrico.is_depot_admin` permission to such users?
> Wouldn't it be possible to have our own `@permission` that looks this up from the depot database table?_

See #200
