### ISSUE TITLE
Area admins with permission can_filter_members don‘t see full list

### ISSUE THREAD

**Issue by nixnuex** [juntagrico/juntagrico#359]
Area admins with permission can_filter_members don‘t see full list of members with filter anymore. They need easy access to mail adress and phone number to contact people that e.g. signed up for a job.

**Comment by nixnuex** [comment]
There seems to be an issue with the filter for depot admins: the member filter lists only a small subset of all subscriptions recipients in that depot.

**Comment by motu55** [comment]
That is a whole different issue
