### ISSUE TITLE
Depot admins do not see send mail button in subscription overview

### ISSUE THREAD

**Issue by nixnuex** [juntagrico/juntagrico#361]
Let's add the button there, too.

**Comment by motu55** [comment]
Its there
https://github.com/juntagrico/juntagrico/blob/02865a4a93ffc3bd0d4866fb4643aec3363fe499/juntagrico/templates/subscriptions.html#L17
It seems to be a permission Problem on your side

**Comment by nixnuex** [comment]
On the members filter the button is there. So this might be a consistency issue.

**Comment by nixnuex** [comment]
And: can_send_mails allows to send to everybody, this is not the intention for depot and area admins.

**Comment by nixnuex** [comment]
The button does not work, users see login prompt.

**Comment by motu55** [comment]
#364

**Comment by nixnuex** [comment]
This is an additional issue. The button does not work. Only the symptoms are identical.
