### ISSUE TITLE
Depot admins do not see all members for depot in member filter

### ISSUE THREAD

**Issue by nixnuex** [juntagrico/juntagrico#362]

**Comment by motu55** [comment]
The method in question sits here
https://github.com/juntagrico/juntagrico/blob/02865a4a93ffc3bd0d4866fb4643aec3363fe499/juntagrico/dao/memberdao.py#L131
Maybe it needs tweeking

**Comment by motu55** [comment]
i tested the the ususal cases for a subscription (active, cancelled and deactivation date in the future)
for primary memberer and co member and it all worked, so i was not able to reproduce.
so best in your system find a case and decribe it here (which dates in the subscription and the subscription membership are set and are they in the future or the past) also make shure the user is not deactivated
