### ISSUE TITLE
Subscription type is not reflected in admin views and filters

### ISSUE THREAD

**Issue by nixnuex** [juntagrico/juntagrico#367]
Currently, a subscription is represented as string like "Einheiten Gemüse:1.0 + Eier 4er-Pack" following the scheme "Einheiten ProductName:Units + ExtraSubscriptions". Here, the string "Einheiten" should be omitted because it does not add any value.

It would be very useful to reflect the SubsriptionTypeName like "Gemüseabo normal (Gemüse:1.0) + Eier 4er-Pack" hence "SubscriptionTypeName (ProductName:Units) + ExtraSubscriptions".

**Comment by motu55** [comment]
See #209 how this should work and for code reuse

**Comment by nixnuex** [comment]
For reuse, you mean `get_part_overview(parts)` to get the string components? Is the proposal for the outcome supported?

**Comment by motu55** [comment]
I went for a setting since it allows more flexibility than doing something smart, which will never cover all cases
