### ISSUE TITLE
Feature Request: Add column "subscription activation date" in assignments list

### ISSUE THREAD

**Issue by puraverdura** [juntagrico/juntagrico#376]
This would be very useful for writting reminder emails at the end of the business year. 

As it is now I have to manually sort out the subscriptions that started somewhere during the business year (opposed to at the start) to not write a reminder email to members that only recently joined.

**Comment by motu55** [comment]
subscription which startet during the business year will have a reduction in the required assignments and can be filtered out using the search criteria builder
