### ISSUE TITLE
Member and subscription filter pages slow

### ISSUE THREAD

**Issue by nixnuex** [juntagrico/juntagrico#378]
Example: Loading the my/subscriptions filter page takes between 25 and >60 seconds to load for about 900 members and django debug-toolbar shows that around 13000 queries are executed to gather the required information. This is because the template walks through all subscriptions in a for loop and accesses related objects. Some heavy prefetch_related might help or a more targeted basic different access structure.

**Comment by motu55** [comment]
the prefetch related will not work since we ilter afterwards, but some select related would be helpfull, i have an idea how to do this
