### ISSUE TITLE
/my/pdf/* not working

### ISSUE THREAD

**Issue by Levino** [juntagrico/juntagrico#387]
Hello again,

I have an installation of this software up and running. However it seems that the /my/pdf/ endpoints are broken. They all result in a 500 server error. Do I need to add a dependency for PDF creation?

Thank you for any hints which might help!

**Comment by Levino** [comment]
Also no luck with `DEBUG = True`. Please also feel free to browser my [source](https://github.com/Levino/juntagrico-serverless).

**Comment by motu55** [comment]
https://juntagrico.readthedocs.io/en/latest/first_steps.html

**Comment by Levino** [comment]
Thank you.
