### ISSUE TITLE
Display contact person for job

### ISSUE THREAD

**Issue by pascalfree** [juntagrico/juntagrico#393]
As suggested by Katja in Slack.

Needs some discussion. I would suggest the following:

- Display area responsible by default
- Have option to override contact in job type and in job instance

Advantage compared to just putting a contact in the description is, that there would always be some contact by default that should at least know whom to forward the request to.

**Comment by motu55** [comment]
I agree with the fact that there is a need to display a contact.
i would just display the area responsible for the moment since this is easy to implement and does not require any data migrations.
if we see that contact overriding is a feature which is in high demand we can still open a new issue

**Comment by motu55** [comment]
so for the moment i would say display the area main coordinator and also the envelope icon to send an email use the existing simple contact form (and sendign mechanism which is used to send a message to the info email address

**Comment by motu55** [comment]
actually we have already have a contact model, its called mebers ;) 
No it is actually ok to do implement it that way.
but to come back to the contact model, it is actually not such a bad idea because we would not have to detect the emails etc from free text which makes the reply to also harder. The question is if a contact is always a person this way we can add the fields to the member.

**Comment by pascalfree** [comment]
Thinking about some use cases:

1. One area responsible writes out jobs for which s/he is the contact person. 
  1. prefers contact via email
  2. prefers contact via phone
  3. Prefers contact via email for questions on area but wants to display phone number and email on job for urgent cases.
2. Multiple area responsible. One is managing the requests on the area in general (by email or phone) and others are responsible for the jobs. E.g. One week person A coordinates the job and one week person B. With a person C jumping in from time to time. For efficient communication they want to show email and phone number on the job of the person that coordinates it.
3. Multiple area responsible. They show a shared email address on the area.
  1. On the jobs they have both their phone numbers
  2. On the job they want to show the shared email address as well. 
4. Multiple area responsible. They want to show both their emails on the area page and on the jobs.

For multiple area members the feature request #340 is pending that should resolve some limitations that make some of the above cases not yet possible. But it also will bring up the question, which coordinator should be displayed on the job.

Member as contact would work for some cases, but it is not granular enough. A member that manages 2 areas might want to have different contact information for each.

I have something like this in mind (from the perspective of an admin):
An inline Form on the job where at least one contact must be defined (or if none is defined it defaults to the area contact). The inline Form has fields:
* email
* phone
* member (to take email or phone from)
* display (selection of: email, phone, emails & phone)

From the first 3 fields at least 1 must be set. If email or phone are not set but should be displayed the members email or phone is used instead.

I guess I just described the "contact" model.

The above inline form could be used on the area, jobtype and job (with overriding character).

To limit the selectable members in that form a permission could be used, s.t. only members with that permission can be selected.

Did I miss something?

**Comment by motu55** [comment]
ok how about this:
a new contact entity with three child classes
one has the fields
- email
- phone
the other has the fields
- member
- display (dropdown selecting which fields of the member shall be selected)
the last one has simply a freetext field which is urlized etc
use the django polymorphic admin integration for the admin part

jobs and jobtypes can have multiple contacts which are dited trough an inline
when it comes to the displaying in the job page display all the contacts in the jobs if the job has no contacts display all the contacts in the jobtype if the jobtype has no contacts display the areas contact information

one open question is wether to display the email adress or hide it behind the contact form

**Comment by pascalfree** [comment]
I was curious how that would like like in the admin. Seems elegant to me:
![grafik](https://user-images.githubusercontent.com/1621900/142741247-43778801-456e-4e90-a5f3-a3d5985bebaa.png)

I made separate entities for email and phone. 
https://github.com/zesinho/juntagrico/pull/1/files

Another open question is, if some (optional) display name should be added for emails and phone numbers to name the person that can be contacted.

**Comment by pascalfree** [comment]
Here some thoughts on the remaining steps to integrate the contacts object

- The email field on the area should be removed and replaced by an email contact field(s).
   - The email in this field is used
      - to send notifications about members joining or leaving the area -> send to all emails from email fields (or to coordinator)
      - to display as contact on the area pages -> replace with full contact info
      - as organizer on the calendar event attached to the job email -> replace with contact of job (first email address if there are many)
      - as an option for the from-email when an area coordinator uses the contact form. -> replace with all emails from email fields
      - as contact information in the job email (if the phone number is not shown) -> replace with same info as is shown on the new job page.
         - We should also set the reply-to email based on the job contact. If no email is given, put the email from job type or area. If there is no email anywhere stick with the default contact email.
- the show_coordinator_phonenumber field on the area should be removed.
   - A sensible default should be used to display the coordinators contact information if no contact information is specified.
- the coordinator field is still needed to specify who has permissions to manage a certain area. Keep as is. (This should become a many to many field in the future)
- If we stay with using the mail form instead of showing the email address, the email contact should have an additional (optional) field for the link text.
- A name to the phone number (and email) could be added using a freetext field.
- Regarding display: a comma should be added automatically (using CSS?) between anything that is not a freetext field. If before or after a freetext field a separator is needed it can be written in the field.

**Comment by pascalfree** [comment]
I added a sorting order for the contact information. The sortable admin does not work with the polymorphic inline, so the implementation is more basic, but works.

further todos:
- [ ] write migrations for email and show_coordinator_phonenumber fields, i.e. create contacts such that the result looks the same as before.
