### ISSUE TITLE
Add to fields to "Mitglieder"

### ISSUE THREAD

**Issue by LouRB** [juntagrico/juntagrico#396]
We need fields added for "Mitglieder" to have well arranged data, which is required by the german "Genossenschafts"-law.
We need two more fields. The field "Notizen" is not enough to handle that.
    **"Grund des Erwerbs"** -> text-field, free to write inside,  plus Drop-Down-Menu with the Options "Gründungsmitglied", "Beitrittserklärung", "Beitritts- und Übertragungserklärung"

   **"Grund der Kündigung"** -> text-field, free to write inside,  plus Drop-Down-Menu with the Options  "Kündigung", "Kündigung und Übertragungserklärung", "Ausschluss", "Tod"

It makes sense that there is still the possibility to fill in nothing, so that other projects who are already running Juntagrico don't get in trouble. 

In the first place, what we need by law for the member-list, in the second place, what might fit. After # it says in which menu it can be found.

    GenoNr. = "Anteilsscheinnummer" (mehrere Anteilsscheine können die gleiche Nummer haben) #Anteilsscheine
    Vorname = "Vorname" #Mitglieder
    Nachname = "Nachname" #Mitglieder
    Straße + HausNr. = "Strasse" #Mitglieder
    Postleihzahl = "PLZ" #Mitglieder
    Ort = "Ort" #Mitglieder
    Tag des Erwebs = "Ausgestellt am" #Anteilsscheine
    Grund des Erwerbs = ??? to be created as "Grund des Erwerbs"
    weitere Geschäftsanteile = "Summe Anteilsscheine" -1 #Anteilsscheine
    Tag der Zulassung = Tag der Zulassung = "Ausgestellt am" #Anteilsscheine
    Tag des Ausscheidens = "Gekündigt auf" #Anteilsscheine
    Grund des Ausscheidens = ??? to be created as "Grund der Kündigung"
    Tag der Eintragung = Erzeugt am (wird automatisch erzeugt bei Erstellung des Anteilsscheins) #Anteilsschein

**Comment by motu55** [comment]
@LouRB just that i understand that correctly a few questions:
-are these field filled out manually by an admin?
- if yes why can't this information be stored for the moment in the notizen field?
- if no how is this field set

also the Member entity does not nescessarily describe a memebership of a cooperation in a legal sense, meaning you can be a member on juntagrico without a "anteilschein" so that each member of a subscription has its own loggin to manage his job assignments.
so all cooperation relevant information is part of the "anteilschein" or at least is calculated out of it (like the fact if someone is a cooperation member or not), which for some reasons is also nit nice for your usecase since a cooperation meber can have multiple "anteilscheine"
This issue will require some more thinking so for a quick solution i would propose the following workarounds for your project:
- use the notizen field and store the date there for the moment
- in your djangoproject which is configuring your juntagrico instance you create an entity with these two field and an one to one raltionship to a member and an admin which suits your needs (dropdown and all) so that a migration will beocome quite easy once we have a solution for this

**Comment by LouRB** [comment]
Tanks for the reply. Yes, this will be filled out by an admin only. Good point.
I don't really want to run a further system parallel, so that's why my goal would be to get it running unless with the option to have the information in Juntagrico as we more or less need it. That makes it also easier for other potential admins more eays to understand it and share responibility. Tha's how I am thinking about the issue at the moment. For me it*s also clear that members can exist within Juntagrico without having "Anteilsscheine" and this is great, exactly what we need!!!
We could export only the members with "Anteilsscheine" and the Information we need, so we have by law what we need. Anyhow it's nice to have some discussions about the issue. I also thought about adding this information to "Anteilsscheine" but that makes less sence, because you would have to change the information for each "Anteilsschein". But I'll think again about it. With the two "Notizen"-fields from "Anteilsschein" and "Mitglieder", I just had one in mind, perhaps that really works and your last point sounds as a solution which might full fill my whish for having the data in a way which makes it possible to integrate it on the Juntagrico layer later.

**Comment by pascalfree** [comment]
Hi.
To me it sounds like the additional fields should really be on the share (Anteilschein).
Not knowing about the german "Genossenschafts"-law, but speculating from what you wrote I guess that there is a way to transfer a share between members. So I imagine this scenario:

- Member A has 2 shares
- Members B as 1 share
- Member A transfers 1 share to member B

In this case you would have to select "Kündigung und Übertragungserklärung" as "Grund der Kündigung" for that share that belonged to member A and then create a share for member B with "Beitritts- und Übertragungserklärung" as "Grund des Erwerbs". I assume you would then use the same "GenoNr" on these shares, to see that it is just 1 share that has been transfered.

For the above example the fields would have to be on the share.

Please correct me if I assumed wrong.

**Comment by motu55** [comment]
Also if amember joins a solawi leaves it for some time rejoins it and then dies while being a member of the solawi this could not be properly be mapped with the fields on the membership.
I can live with the fields on the share, if we can create freetext dropdowns in the admin i do not know but we would have to investigate that, but if we can agree on the fields on the share i at least can add them in the 1.4.0 release and the display and handling can then be refined in a 1.4.x release

a side question why not use the id of the database for the geno nr? I know this would require some transition work but this would be a one of

**Comment by LouRB** [comment]
top. Adding this at "share" was my first idea too, somehow I got away from that. I think this would be fine also. Freetext is not needed in the end, if we have all options in mind and I think we have that. 

answer to the side question:
We already have about 400 members, i'll think about the ID, but at the moment, I have the feeling this will bring a lot of trouble.
