### ISSUE TITLE
Assignement reduction for mid-year subscriptions

### ISSUE THREAD

**Issue by pascalfree** [juntagrico/juntagrico#40]
As we (and probably many initiatives that are just starting) usually have many subscriptions starting during the season, we decided to reduce the price and number of required assignments for a subscription based on the month, when members joined. This is not reflected during signup and in the E-mail with the bill, nor in the required number of assignments shown in the user menu.
In our case it would be enough to be able to set the price/assignments depending on month when joined. The reduction might be non-linear.
This is not an urgent feature. At the moment we show the current prices on our website instead.

**Comment by motu55** [comment]
For legal reason i would not display a reduced price during signup. Also the bills should allready do a linear reduction. but the billing will probably move into a separate app. so the thing applies to the assignments therefore i changed the title of the issue.
this can clearly be done
by extending this method
https://github.com/juntagrico/juntagrico/blob/master/juntagrico/entity/subs.py#L192

 basically check if the activation date is greater than the start of the current business year
https://github.com/juntagrico/juntagrico/blob/master/juntagrico/util/temporal.py#L27

and if this is the case return a floating point between 0 and 1 representing the percentage of days remaining

even better create a helper method for that here
https://github.com/juntagrico/juntagrico/blob/master/juntagrico/util/temporal.py
with a meaningfull name which can be reused in the billing process as well

i think you can extract the code from here
https://github.com/juntagrico/juntagrico/blob/master/juntagrico/util/bills.py#L39

 and in the end call the new helper funtion in there
