### ISSUE TITLE
Rich text editor for description fields

### ISSUE THREAD

**Issue by motu55** [juntagrico/juntagrico#400]
At the moment our text field which are used for descriptions and other long texts  ar plain texts with urlize and linebrak filters in the themplate
in some cases it might be beneficial to have more styling options
so a richtext editor and a safe filter in the templates would be a good idea
meh als gmües uses ckeditor for that
before we add somethin we should gather a list of pissibilities and evaluate which one is the best

**Comment by pascalfree** [comment]
This seems flexible enough to leave the choice to the instances: https://pypi.org/project/django-richtextfield/

We should probably define a default though.

**Comment by motu55** [comment]
i see the idea behind the requirement for a configurable editor, on the other hand as you said we should at least document a default since most cooperatives do not have the expertise to find one for themselves and there is the question what will be the default.

**Comment by motu55** [comment]
i just saw that we use tyni mce in the mailer so we already ship that with the package so if you do not object i would use this as the default
