### ISSUE TITLE
Texts which would be nice to be adaptable or extendable

### ISSUE THREAD

**Issue by motu55** [juntagrico/juntagrico#411]
A collection of texts which would be nice if they could be adapted or extended

Rules to add a text:

- **check if your text was already mentioned**
- add a screenshot highliting the text or containing an arrow where a new text should go
- give some context if needed
- **check if your text was already mentioned**

**Comment by motu55** [comment]
example contribution
![grafik](https://user-images.githubusercontent.com/3921256/117169083-1064b800-adc9-11eb-8e5b-4fbffe9a6170.png)
the main text under "tätigkeitsbereiche"

**Comment by jolling-eg** [comment]
![Bildschirmfoto 2021-05-10 um 09 55 10](https://user-images.githubusercontent.com/59708658/117625074-ecf98e80-b175-11eb-9cdf-9cecfd8a036e.png)
Wäre Toll wenn man hier anstatt "Tasche" "Kiste" wählen könnte

**Comment by Erdmut** [comment]
![böhnli](https://user-images.githubusercontent.com/83092009/117923732-de85b100-b2f4-11eb-9220-ca34ef335bb8.jpg)
text under "Arbeitseinsatz melden" (in the juntagrico_assignment_request)

**Comment by Erdmut** [comment]
![Bildschirmfoto_2021-10-03_22-19-45](https://user-images.githubusercontent.com/83092009/135770682-b49f9f9e-3ee7-490d-ab2a-f931e5dcfb74.jpg)

**Comment by padili** [comment]
For the juntagrico_assignment_requests there is at least on entity to bring to the vocabulary > Böhnli

![image](https://user-images.githubusercontent.com/25586157/136674679-68042e91-1756-4621-89f2-5544c0e2c5c0.png)

Eventualy i can give a hand on implementing that :) @motu55

**Comment by pascalfree** [comment]
> For the juntagrico_assignment_requests there is at least on entity to bring to the vocabulary > Böhnli
> 
> ![image](https://user-images.githubusercontent.com/25586157/136674679-68042e91-1756-4621-89f2-5544c0e2c5c0.png)
> 
> Eventualy i can give a hand on implementing that :) @motu55 

Would you use "Arbeitseinsatz" here? If yes I would rather change it to that entirely.

**Comment by pascalfree** [comment]
> 
> 
> > Would you use "Arbeitseinsatz" here? If yes I would rather change it to that entirely.
> 
> Yes, either 'Arbeitseinsatz' or 'assignment'/'assignment_pl' from the vocabulary.

Oh I missed that this setting already exists. Feel free to contribute: https://github.com/juntagrico/juntagrico-assignment-request

**Comment by pascalfree** [comment]
Not sure if this is also the right place to talk about possible implementations.
I would suggest to store the text overrides in the database to make it accessible to non-IT admins. If there are performance concerns we can add some simple caching.

**Comment by padili** [comment]
> 
> 
> Not sure if this is also the right place to talk about possible implementations. I would suggest to store the text overrides in the database to make it accessible to non-IT admins. If there are performance concerns we can add some simple caching.

@pascalfree as I'm new to Django and Python i have to go the simple way that i can just copy&paste and build up knowhow 😄 
For an improvement point of view I agree totally, but then its a bigger thing, as all vocabulary has to go to the DB system wide. Otherwise it is hard to see what is to maintain where 🤔  
So later (really later) on I might be able to manage this 😄

**Comment by pascalfree** [comment]
@padili 
The reason I want to have text overrides to be accessible to non-IT admins (or make it simpler for IT-admins) is that we want to adjust some text multiple times a year based on some current strategies (i.e. we need more shares) and I'm too lazy to do that all the time.
The vocabulary should not change that often, which is why I would leave it a setting in the code.

**Comment by pascalfree** [comment]
Closing with #730, which puts template blocks in place to adjust all above mentioned text sections using [template overrides](https://juntagrico.readthedocs.io/en/releases-1.7/reference/templates.html).
Please open a new issue, if you find other text sections you would like to adjust.
