### ISSUE TITLE
Unpin dependencies in requirements.txt

### ISSUE THREAD

**Issue by 1resu** [juntagrico/juntagrico#414]
Every dependency in the `requirements.txt` file is pinned. This prevents updates by simple run `pip install --upgrade -r requirements.txt` which is imho critical for security reasons.

It would be nice to pin these dependencies at least to the current stable series, e.g. `Django>=3.2.0,<3.3.0`

**Comment by motu55** [comment]
This is a valid point, at least for django
we have to define which dependencies we can unpin and which not because some of the need to be pinned
