### ISSUE TITLE
Give new members a field for comments during sign up

### ISSUE THREAD

**Issue by pascalfree** [juntagrico/juntagrico#417]
While signing up members might have additional questions or comments.

Also it might be interesting to ask the new member how they found the cooperative and who referred them.

The later is especially useful while we handout assignments for referrals as a promotion measure.

It is probably enough to just include the comment in the email to the admin and not store it in the db.

The text/question above the text box should be ajustable.

**Comment by motu55** [comment]
ready for the comment field
only add it to the email, no db is involved
for the referer info open a new issue
