### ISSUE TITLE
Wrong domain in password reset email

### ISSUE THREAD

**Issue by patrickuhlmann** [juntagrico/juntagrico#418]
Hi

Our site was unable to send the send the emails as the sender was set to webmaster@localhost. We then found out that django uses DEFAULT_FROM_EMAIL to set this sender.

I think it would make sense to either document this behavior or initialize the setting from the INFO_EMAIL setting.

Anyways, the mail could then be sent but the subject was "Passwort auf example.com zurücksetzen". I tried to analyze the behavior. It seems that django is using the value from the default site (which it initializes to example.com). Unfortunately I was unable to change it. Also the parameter DEFAULT_FROM_DOMAIN which should change it did not work. Do you have any idea how to change it?

Also here I think it would make sense to either document the behavior or initialize the setting from the SERVER_URL setting.

My configuration:
https://github.com/gartenbergCH/gartenberg/blob/master/gartenberg/settings.py

**Comment by patrickuhlmann** [comment]
The site can be changed in the "Datenverwaltung" under "Website"

**Comment by motu55** [comment]
this will go into the documentation unless someone has an idea how ti fix this in the code

**Comment by pascalfree** [comment]
While we add that we might as well let it replace the settings ADMINPORTAL_SERVER_URL and ADMINPORTAL_NAME
i.e. these could be loaded from what is defined on the site.
