### ISSUE TITLE
Suggestion: For administration / members: enable search by address and city (or postal code).

### ISSUE THREAD

**Issue by gako-li** [juntagrico/juntagrico#419]
Suggestion: For administration / members: enable search by address and city (or postal code).

**Comment by pascalfree** [comment]
I agree that this would be useful.

As a workaround you may want to use the excel export of the members (my/export) and filter it there.

**Comment by motu55** [comment]
adding the fields to the search is easy, will we also display them in the overview in the admin?
alternatively we could add the pencil icon to the meber filtering, and add the adress again there

**Comment by gako-li** [comment]
Address & city would be nice also to display. Any solution is welcome, thanks.
