### ISSUE TITLE
More filter options on the assignments overview

### ISSUE THREAD

**Issue by pascalfree** [juntagrico/juntagrico#424]
We use the assignments overview primarily to find members that have done only few jobs at some point in the season and send them a reminder.
For that it would be useful to filter out:

* Members who already cancelled their subscription (but are not deactivated yet). Technically they should do their assignments, but maybe they moved away and might not be amused about the reminder.
* Members that startet recently. They might not have had the time to come yet.

For that it would be useful to have the columns "active" (if the subscription is not cancelled) and "starting date" (of the subscription) in the table.

**Comment by motu55** [comment]
use the state instead of a active flag
