### ISSUE TITLE
Custom pagewide scripts

### ISSUE THREAD

**Issue by pascalfree** [juntagrico/juntagrico#427]
There is currently no clean way for an instance to add javascript code that is active on all pages.
I propose 2 new settings:

* A "SCRIPT" setting, equivalent to the "STYLE_SHEET" setting, that loads some custom scripts at the end of base.html (before the script block)
* A "DYNAMIC_SCRIPT" setting, that (if set) includes a template before the SCRIPT in base.html. This is supposed to have a template that moves data from django to javascript equivalent to i18n.js. One use case is to pass urls generated from the "{% url "..." %}" template tag to js.

**Comment by motu55** [comment]
apart from a better name for DYNAMIC_SCRIPT not a bad idea
also both could be combined in a template where scripts are loaded so multiple js scripts could be loaded
the same goes for the css part
