### ISSUE TITLE
Assignment Search Builder not working with WebKit

### ISSUE THREAD

**Issue by nixnuex** [juntagrico/juntagrico#431]
The second field selection ("equal", "less than", ...) is always reset on Safari (macOS and iOS) preventing the filter from functioning as expected. On eg Firefox everything is fine. Might there be a fixed version?

**Comment by pascalfree** [comment]
Can you try the newest versions of datatables and extensions (download [here](https://datatables.net/download/#bs4/dt-1.10.23/r-2.2.7/sb-1.0.1))?

**Comment by pascalfree** [comment]
Ok. I tried. It's even worse in the new version.
You could file a bug in https://github.com/DataTables/SearchBuilder

**Comment by pascalfree** [comment]
Ok I tried version 1.2.0 and a few hours later 1.2.1 was released with the fix. ;-)
