### ISSUE TITLE
Sorting for the status column in the "Arbeitseinsätze" screen

### ISSUE THREAD

**Issue by PaulKC** [juntagrico/juntagrico#439]
The sorting for the status column in the "Arbeitseinsätze" screen is broken.

![image](https://user-images.githubusercontent.com/5611775/134724221-5a38fa9b-65a3-4346-97d5-6473ead04cbd.png)

**Comment by pascalfree** [comment]
It seems that datatables does not recognize this localized comma as a floating point.
I went for the easiest solution and removed the decimal.
