### ISSUE TITLE
Switching of subscription very (too) complex

### ISSUE THREAD

**Issue by nixnuex** [juntagrico/juntagrico#440]
Imagine a user being the owner of a subscription with a main subscription part shared among different people. The required shares are fulfilled. This user wants to switch his subscription to a different option with the same amount of required shares. He is expecting the Subscription -> Change Subscription -> Change Subscription Part to do the job. He scrolls down to "Order subscription parts" and wants to add the new subscription. He gets an error that there are not enough shares. Then he finds the "Cancel subscription completely" at the top of the page. He clicks and confirms and is suddenly locked out of the "Change Subscription Part" where he expected to add the new option. He can now go through Subscription -> Order New Subscription but has to set up everything from scratch (depot, extras, ...) and he even has to add all other members manually.

The question here is, what is the limit of a subscription? How should changes be handled? Technically, a subscription part ending on Dec 31 could be combined with a different starting the day after on Jan 01. But currently the user has no easy way to execute this on his own. He has to go through canceling the whole subscription.

Any idea how this could be improved?

**Comment by pascalfree** [comment]
If I read this right, the issue was, that an existing part should have been canceled first (before ordering a new one), but the user chose the wrong button to do so?

**Comment by nixnuex** [comment]
Additional but related behavior: Currently, the subscription part cancellation button is not displayed for the single (main) subscription as the user is guided to the whole subscription cancellation at the bottom of the page. An extra subscription seems to break the logic and the cancellation button is then displayed for all main and extra subscriptions. Also: extra subscriptions seem to break the blackout period logic e.g. the buttons are displayed even during the blackout period from Oct-Dec.

**Comment by pascalfree** [comment]
Also consider #554

**Comment by pascalfree** [comment]
> Additional but related behavior: Currently, the subscription part cancellation button is not displayed for the single (main) subscription as the user is guided to the whole subscription cancellation at the bottom of the page. An extra subscription seems to break the logic and the cancellation button is then displayed for all main and extra subscriptions. Also: extra subscriptions seem to break the blackout period logic e.g. the buttons are displayed even during the blackout period from Oct-Dec.

There is no blackout period anymore since version 1.4.2.
The extra sub bug still persists. I added a fix to #490
