### ISSUE TITLE
Add recipients for administrative emails

### ISSUE THREAD

**Issue by pascalfree** [juntagrico/juntagrico#46]
E-mails about new members, subscriptions, subscription cancellations etc. might be of interest to one or more people in the administration. So far most of these email are sent to the "info"-address which then has to forward it manually.

It would be convenient to set recipients of such emails individually.
This could be done through user/group permissions.

**Comment by motu55** [comment]
this is for new subscriptions already implemented
https://github.com/juntagrico/juntagrico/blob/master/juntagrico/mailer.py#L139
using this
https://github.com/juntagrico/juntagrico/blob/master/juntagrico/models.py#L26
this can be extended to more stuff or extend existing methods

**Comment by pascalfree** [comment]
Thanks.

In our case we need this function for `send_subscription_canceled` and `send_membership_canceled`.
Also we might want to get a separate admin email when a share is created, as these might be created without a subscription. At least the amount of shares ordered should be mentioned in an admin email.
Also this subject should probably read "Abo" instead of "Anteilschein"
https://github.com/juntagrico/juntagrico/blob/58e2156fbe3b5ec235e911bf09f6b25403ff2136/juntagrico/mailer.py#L154

**Comment by pascalfree** [comment]
Implementation ongoing on branch [`mailer_cleanup`](https://github.com/juntagrico/juntagrico/tree/mailer_cleanup).

Todo:
- [ ] Create [signals](https://github.com/juntagrico/juntagrico/blob/mailer_cleanup/juntagrico/signals.py) member_created and sub_created
- [ ] Trigger signals in [`lifecycle`](https://github.com/juntagrico/juntagrico/tree/mailer_cleanup/juntagrico/lifecycle)
- [ ] Connect signals to admin notifiers 

Connecting should probably happen in `AppConfig.read()`. See warning here https://docs.djangoproject.com/en/2.2/topics/signals/#connecting-receiver-functions

**Comment by motu55** [comment]
deactivation notification could not be triggered through lifecycle since the message would be missing
other wise it should be all there except maybe the admin notifiers where i was not shure if there was something missing since i found all (except the share canceled but this is covered by the mebership canceling which goes hand in hand)
i did the signal connectig the old fashioned way and in accordance with the existing naming scheme.
