### ISSUE TITLE
Add Member Number

### ISSUE THREAD

**Issue by LouRB** [juntagrico/juntagrico#463]
The members should have a quick (!) overview about all relevant data / numbers etc. concerning their membership.

1. Add form "Anteilschein" /  "Anteilschein-Nr." as "Mitglieds-Nr.:" in view for members in menu "Abo"

2. add form "Abo-Typ": "Name" and "Größe" and from "Abo-Produkt": "Name"
final information for exampel -> "Abo: J05 1xGemüse" in view for members in menu "Abo"

3. add from "Abo-Typ": "Preis" as "Monatlicher Beitrag:"
-> Monatlicher Beitrag: 90,00€ in view for members in menu "Abo"

**Comment by pascalfree** [comment]
Thanks for your suggestions.
Here some questions and possible solutions.

1. You mean to show a list of the share numbers instead of just the total count? Currently the numbers are one click away from that page. Isn't that enough? About calling it "Mitglieder-Nr." members might have more than 1 share in general, don't they in your case?

2. The display of the subscription name can be modified with the SUB_OVERVIEW_FORMAT setting https://juntagrico.readthedocs.io/en/latest/settings.html#sub-overview-format

3. Probably the easiest would be to include the monthly price in your subscription type name. Do you actually bill the subscriptions monthly and can they be canceled monthly?

**Comment by LouRB** [comment]
Thanks for your questions.

1. I*m not sure how other projects are using that. For us the field "Anteilschein Nummer" ( a field where we can insert any number we want) is the relevant one. So a person can have also several Anteilsscheine, but the "Anteilschein Nummer" is always the same. It's true the number is just one click away. I would prefer to have it in the general overview. :-)  But if that makes no sense for other projects we perhaps change it only in our installation.

2. I'll ask our IT to find out, if that is, what we need. :-)

3. Not sure if I understand what you mean. For us it would be nice too keep the price as a separate value. The price is the price per month. Regularly people can just leave, cancel and join once a year. We are exporting the data as .csv and the tax office uses the information as import for their DATEV to check how payed and who didn't. So adding it to the field subscription type name seems not what we would need.

**Comment by pascalfree** [comment]
1. It might be worth to implement a field on the member for such a custom member number. Where else do you use that number in the system? And in which exports must it appear?

2. 👌

3. Ok. So if I understand correctly, as the price in the "price" field of the subscription type you put the yearly price e.g. 1080€. (the system currently expects the yearly price there). But in the overview you want it to show with the monthly price? Would the yearly price also be ok here?

**Comment by pascalfree** [comment]
I remember this issue where we were talking about a GenoNr. #396
Just to confirm that this is not the same as the MitgliederNr. that you mention here. It shouldn't, I think.

**Comment by LouRB** [comment]
Sorry. GenoNr = MitgliederNr.

1. "Anteilschein Nummer" works for as at the moment. We have a nice export-list, which schows "Anteilschein Nummmer" as Geno-Nr.. But now I understand why this might bring trouble to other projects if the use "Anteilschein Nummer" in a different way. If they use the field in a different way, it's not clear what should be shown in the overview.

3. Ah okay. The system expects the price per year. We are using it as price per month. :-) which works fine for us so far. [Perhaps because we don't use billing via juntagrico?] So price would be nice, even if we use it as monthly.

**Comment by pascalfree** [comment]
1. I see. Then the proper solution would be to have that optional member nr. field in the member itself and then display it on the overview and the relevant exports.
Do the geno numbers follow a certain pattern?

2. I think in the core only the order summary page assumes that it is a yearly price and shows "/Jahr" you might have overridden that. Do you then also bill your members monthly or is this just for the displayed price?
With the billing extension I'm not familiar enough.

**Comment by LouRB** [comment]
1. Well we started at number one and are now at 450 :-) There is no such number in switzerland as it seems?
2. Most of our members pay monthly. Not sure if I had a look at the order summary page, I'll keep eyes open :-)

**Comment by LouRB** [comment]
So, regarding that poin:

add form "Abo-Typ": "Name" and "Größe" and from "Abo-Produkt": "Name"
final information for exampel -> "Abo: J05 1xGemüse" in view for members in menu "Abo"

The information would have to be changed here:
https://github.com/juntagrico/juntagrico/blob/a3c73dfe20a7da68f017a216b70d3b435383d07b/juntagrico/templatetags/juntagrico/subscription.py#L15

But if it doesn't make sense for other CSAs too, we'll change that locally?

**Comment by LouRB** [comment]
@pascalfree So, what do you think?

**Comment by pascalfree** [comment]
Regarding the list of subscription parts:
You can achieve:
"1xAbo: J05 Gemüse"
by setting the long name of the subscription type to "Abo: J05 Gemüse".
How is your structure? What Products, Sizes and Types do you have?

1. I'll introduce a "member number" field for the 1.5 release then we can display it, if it is set.
2. Would you want the total price displayed on the page or the price on each part in the list? Or both? I would use the label "Betriebsbeitrag" as in the order process. Does that work for you? This is actually more complicated if there are (extra) parts that have custom billing periods. We'll figure it out.
Regarding "yearly" or "monthly", a setting might do it. I'll think about it.

**Comment by LouRB** [comment]
> Regarding the list of subscription parts: You can achieve: "1xAbo: J05 Gemüse" by setting the long name of the subscription type to "Abo: J05 Gemüse". How is your structure? What Products, Sizes and Types do you have?

We only have "Gemüse" as product, sizes from 0,5 to 8, ... with the types we did a kind of workaround: we defindes about 280 types = the amount of shares we have, because each might have a different price. So Typ-Name is a kind of individual share-Name. So members have an individual Genossenschaftsnummer and are part of a veggie-share, for example A12 or Z05 or T12. Anyhow, we can change that point locally.

>     1. I'll introduce a "member number" field for the 1.5 release then we can display it, if it is set.

**Thanks for that.**
> 
>     2. Would you want the total price displayed on the page or the price on each part in the list? Or both?
Nor sure if I understand what you mean, but the price on the page would be great. For the lists and exports we anyhow did our own stuff.

I would use the label "Betriebsbeitrag" as in the order process. Does that work for you? **YES**
This is actually more complicated if there are (extra) parts that have custom billing periods. We'll figure it out.
>        Regarding "yearly" or "monthly", a setting might do it. I'll think about it.

**Comment by pascalfree** [comment]
Ok I just found that you use the "Bietrunde". I think it would be helpful if juntagrico could handle that approach better.
I opened a new issue for that. #503 Please add comments there if you see additional requirements.

What does the A and the 12 stand for in A12? Or in other words how do you make up these names? And are these the names of your subscription types?

I assume your members can only have one subscription part of maximum size 8 and can't accumulate them. That's why the total price for you is the same as the part price.

**Comment by LouRB** [comment]
> Ok I just found that you use the "Bietrunde". I think it would be helpful if juntagrico could handle that approach better. I opened a new issue for that. #503 Please add comments there if you see additional requirements.

Oh, sorry. I could have told that. Makes things more clear. For me "Bietrunde" is so common, that the I sometime forget, that other CSA-projects don't work with it :-). 

> What does the A and the 12 stand for in A12? Or in other words how do you make up these names? And are these the names of your subscription types?

Yes. It's the name of subscription type.
Well...Actually it's not the most intelligent system...but someone started it and so far we didn't change it. Usually it's the first letter of the last name and then just the number (started with one and so on). But the idea of having some kind of ID for the "Gemüseanteil" works quite fine for us, also in combination with that kind of workaround, which actually does what it should!!
 
> I assume your members can only have one subscription part of maximum size 8 and can't accumulate them. That's why the total price for you is the same as the part price.
Right.

**Comment by pascalfree** [comment]
So what I understood by now is that you give each of your subscriptions a name, e.g. A12. If it would be ok to show that name on the Depot list, you could use the field "Spitzname" on the Subscription for that. I think that is easier than creating 1 type for each subscription. However you need different prices per type, that will be fixed by #503 eventually. Also point 3 would need #503 to show the proper price. So far the system assumes the yearly price. That will be fixed with #467.

# TODO

* [ ] show member number in admin and to user, if it is set. In the Membership page. Also in other pages?

**Comment by pascalfree** [comment]
Closing this issue with #737. Related issues will be followed up separately. See previous comments.
