### ISSUE TITLE
Wrong calculation of membership cancellation date on business year start

### ISSUE THREAD

**Issue by nixnuex** [juntagrico/juntagrico#472]
On the first day of the business year (in our case January 1st) the calculation of the next membership cancellation date is wrong and allows cancelation one year too early.

**Comment by pascalfree** [comment]
Which version are you using?
This was fixed in 1.4.4 #468 I think.

**Comment by nixnuex** [comment]
True! Got this as user report and did the redeploy afterwards. So this seems to be fixed.
