### ISSUE TITLE
Add Information to 'Meine Einsätze'

### ISSUE THREAD

**Issue by padili** [juntagrico/juntagrico#487]
The page 'Meine Einsätze' shows actually not so many information as it could be interesting for the user.
![image](https://user-images.githubusercontent.com/25586157/149834475-b10cfc75-f274-4f42-8a0e-0c0e0304fc89.png)

the idea is to keep the design like for the other jobs pages with the list.
So for 'Meine Einsätze' show my jobs with the spent hours (eg.):
![image](https://user-images.githubusercontent.com/25586157/149834160-e1552d92-b0db-4747-b996-7a6c2d93c317.png)

a total of the hours (for the search) on the bottom would be very nice. 
Luxus variant is the total depending on the business year like 6h/18h ... but not necessary at this is visible in the sidebar with the bars.

**Comment by padili** [comment]
one more requirement is to not show jobs with 0h 
or have a switch on a job to have it only for signing in for the job.
this is eventually an other issue (feature)

**Comment by pascalfree** [comment]
The last point is a separate feature. Please open a new issue for that.

I agree with the other suggestions you made.

**Comment by Erdmut** [comment]
Da diese Darstellung von "Meine Einsätze" bei uns nach wie vor recht viel Verwirrung bei den Mitgliedern auslöst hat es für uns eine sehr hohe Bedeutung, hier eine Lösung zu finden.

Wenn die im System erfassten geleisteten Einheiten in einer weiteren Spalte ergänzt werden, (und allenfalls summiert) wäre uns schon sehr viel geholfen.  Da die reine Zeitspanne ja noch nicht aussagt, wie die Wertigkeit am Ende ist bzw. den Wert von "Arbeitseinsat vielfaches" nicht in der Darstellung berücksichtigt.  Ich denke das könnte für die meisten Instanzen hilfreich sein?

**Comment by pascalfree** [comment]
Gelöst mit #735.
