### ISSUE TITLE
Collapse the subscription description in registration and size change

### ISSUE THREAD

**Issue by pascalfree** [juntagrico/juntagrico#50]
Due to long subscription type descriptions (in our case) the registration page to select the sub requires too much scrolling and the form becomes unintuitive, especially on mobile. Would be nice to have the text collapsed to one line initially with a link "more" that expands it.

**Comment by motu55** [comment]
do you mean this
https://github.com/juntagrico/juntagrico/blob/master/juntagrico/templates/createsubscription/select_subscription.html#L25
or this
https://github.com/juntagrico/juntagrico/blob/master/juntagrico/templates/createsubscription/select_subscription.html#L43

(the same aplies for the create subscription of course)

**Comment by pascalfree** [comment]
In our case the second one
https://github.com/juntagrico/juntagrico/blob/master/juntagrico/templates/createsubscription/select_subscription.html#L43
But for others the first one might be the problem.

Some custom javascript could do the trick. But HTML divs/spans and css class around the description would help.

**Comment by pascalfree** [comment]
With the new subscription "product", I could move the parts of the subscription description that where common for all subs to the description of the product, shown on the top.
For us the issue is solved and I close it.
