### ISSUE TITLE
Instance specific description on recurring job

### ISSUE THREAD

**Issue by pascalfree** [juntagrico/juntagrico#51]
The description of recurring jobs is usually kept vague in order to allow its continuous re-usage.
It would be nice to be able to add an additional description to a specific instance of the job, to give some specific information or point out anomalies.
This would be displayed below the normal description and get a css class or id to style it if desired.

**Comment by motu55** [comment]
in my experience anomalies and such stuff are comunicate by email to the people doing the job to be sure that they received the information
but we coudl add an additional description field to a instance of a recuring job, but i worry a bit, that this would confuse the users.

**Comment by pascalfree** [comment]
I think there might be situations, where it is desirable to inform the members before they assign themselves to a job. Confusion should be preventable with good highlighting and clear wording.
It is probably a low priority feature.
