### ISSUE TITLE
Polls

### ISSUE THREAD

**Issue by pascalfree** [juntagrico/juntagrico#53]
Sometimes it would be great to get quick feedback of the members on some ideas or plans.
For this, polls would be a nice feature.

To get high response rates this should be possible with only 1 click for the member.

Distribution of the poll could happen in multiple ways (simultaneously):
1. A template with links can be generated to be included in the email newsletter. These links would directly count the vote (if the member is logged in).
2. The poll is shown to any member visiting juntagrico that has not voted yet. There is an option to dismiss.

Anonymous (but 1 per person) voting should be an option.

This could be an extension.

**Comment by motu55** [comment]
i think before we reinvent the wheel we should evaluate a thirdparty solution like one if these
https://djangopackages.org/grids/g/polls/
and if they do nott suffise evaluate if it would make more sense to contribute to an existing solution

**Comment by pascalfree** [comment]
I agree.
Just for distribution method 2 a juntagrico extension might be useful for integration.

**Comment by motu55** [comment]
this seems to have gone stale so i close it for now

**Comment by pascalfree** [comment]
If anybody stumbles upon this. You may be interested in this: https://github.com/nixnuex/juntagrico-polling
