### ISSUE TITLE
Add configuration for membership cancellation notice period

### ISSUE THREAD

**Issue by nixnuex** [juntagrico/juntagrico#536]
As far as I can see, we currently don't have any configuration for the notice period (number of month before next cancellation date) for the membership. So members can cancel their membership a day before the end of the `MEMBERSHIP_END_MONTH` although most coops might have several month of notice period stated in their conditions. There is even a wrong comparison to the subscription annual cancellation month `BUSINESS_YEAR_CANCELATION_MONTH`.

Proposal: Add configuration option `MEMBERSHIP_END_NOTICE_PERIOD` in months and adapt logic accordingly.

**Comment by pascalfree** [comment]
Yes the MEMBERSHIP_END_MONTH setting is weird.
I would expect that the membership always ends with the business year. Doesn't it in your case? In that case we would only need one setting.

For some consistency the new setting should be called MEMBERSHIP_CANCELLATION_MONTH
