### ISSUE TITLE
Activity area overview neglects new contact details option

### ISSUE THREAD

**Issue by nixnuex** [juntagrico/juntagrico#541]
In the activity area overview, the contact details are still taken from the coordinator. This is counter intuitive, as the activity area details page only lists the new contact info options. Shouldn't the overview also display the new style info?

**Comment by pascalfree** [comment]
This looks correct in my instance and the code.
The displayed info falls back to the coordinator info, if no contact is specified.
Are you using a template override?

**Comment by nixnuex** [comment]
True, it was the template overwrite...
