### ISSUE TITLE
Feature Request: If an AboType does not require a share, don't ask for signing a share in the registration process

### ISSUE THREAD

**Issue by padili** [juntagrico/juntagrico#543]
It is possible to create abo-types that don't require a share, what is very use full.
**Actual**
At the moment during the registration process, the user needs to sign a share to complete the registration.
After giving the member informations the apo-type is shown:
![image](https://user-images.githubusercontent.com/25586157/166105340-a8c87835-0489-4c6a-8fed-7f767758f69d.png)
after selecting the depot the share is shown (select 0 shares is not possible):
![image](https://user-images.githubusercontent.com/25586157/166105350-7e4d9f77-440b-4075-bad8-513d340977a7.png)

**Expected**
it would be great to check on the chosen abo-type if a share is required or not and show the signing of the share in consequence.

**Comment by pascalfree** [comment]
In theory the member needs a share to be a member legally speaking.

But we might want to open the door for people who just want a login to have a look and receive newsletters etc.

I would add that information on the Form and a button to create an account without membership (only if no subscription was selected), such that is clear to the registering user what 0 shares imply.

Or the info is only shown if 0 shares are entered in the field.

**Comment by pascalfree** [comment]
This is solved by #667
