### ISSUE TITLE
Allow links in the description in the data management

### ISSUE THREAD

**Issue by patrickuhlmann** [juntagrico/juntagrico#547]
It would be useful if we could add links in the description fields in the data management.

A scenario:
We currently have no more spots for one of our "products". Thus we wanted to write in the description of said Abo-Produkt that there is a waiting list and you can send an email to xyz to be on the list. Unfortunately we could not make the link clickable.

Possible solutions:
- Allow all HTML -> probably not a good idea
-Allow some tags -> might be hard to filter
- Allow markdown and convert it to html -> could be quite nice also for other formatting on the other hand some people that don't know markdown might be surprised when they write some text and it is displayed "special".

**Comment by pascalfree** [comment]
Hi Patrick

Which version are you using?

If you put a full link starting with `https://` it should be recognized and clickable.

There is also the option to enable the rich text editor for all text field using these instructions.
https://juntagrico.readthedocs.io/en/latest/rich_text_editor.html

Let me know, if that works for you.

**Comment by patrickuhlmann** [comment]
We are using the latest version. Actually I wasn't trying to just put the link but directly tried to put html-code. It works as you said. If we just put the link with https://, it is clickable. Sorry for the inconvenience.
