### ISSUE TITLE
Add Option for "Reson for Signing Share"

### ISSUE THREAD

**Issue by LouRB** [juntagrico/juntagrico#556]
so if possible there two more options to be added (remembering this issue https://github.com/juntagrico/juntagrico/issues/396). reality is more complex ;-)
new options:
"Erhöhung der Anteile"
"Betriebsbeteiligung - Lohn"

**Comment by LouRB** [comment]
Hard to answer. Before I thought there are not so many options. AND I think there are not really (many) more again :-)
"Erhöhung der Anteile"
"Betriebsbeteiligung - Lohn"
"Übertragungserklärung"
 In the beginning I thought drop down plus possibility to type in free text would be good. Because we are also still learning to govern the Genossenschafts-ship.

**Comment by pascalfree** [comment]
will come with 1.6
