### ISSUE TITLE
Extend admin view of member

### ISSUE THREAD

**Issue by pascalfree** [juntagrico/juntagrico#56]
Currently the full information for one member has to be collected through multiple clicks and searches in the admin interface. To simplify that, more information could be shown on the edit member page in the admin interface.
The following information should be added:

- Active Subscriptiontype(s) with amounts and price of each
- Current Depot
- Share(s): Amount and possibly links to edit them

This information does not need to be editable on the member page, but could.

**Comment by motu55** [comment]
I see the bennefit of reverse link to the shares 
I do not see the benefit of the depot (an usecase where this would be helpfull)
The subscription types are already there in the subscription description, while i would understand the sum of the prices as information i do not see why it would be usefull to have the price of each.

**Comment by motu55** [comment]
we reduce this issue to the shares. the whole price issue will be handled by the juntagrico billing addon
