### ISSUE TITLE
Lesbarkeit Mitgliederliste verbessern

### ISSUE THREAD

**Issue by patrickuhlmann** [juntagrico/juntagrico#576]
Wenn ich unter Administration auf Mitglieder/Alle klicke sieht es so aus (Bild ist Orignalgrösse):

![image](https://user-images.githubusercontent.com/511373/208458866-637bf040-8722-4abe-a415-737eed330110.png)

Einerseits ist die Schrift sehr klein und andererseits mit grün auf grün kaum lesbar. Allgemein sind die Links in der Applikation häufig grün auf grün. Könnte man da vielleicht den Kontrast etwas erhöhen und auch die Schriftgrösse?

**Comment by pascalfree** [comment]
Da braucht man tatsächlich gute Augen.
Bei unserer Instanz haben wir mit css eine etwas kontrastreiche Farbe per CSS eingestellt:
```
a {
    color: #753D18;
}
```
Die Schriftgrösse in der Tabelle könnte so angepasst werden:
```
#filter table {
  font-size: 12pt;
}
```

Ich plan es für 1.5.6 ein.
