### ISSUE TITLE
Delivery Tours

### ISSUE THREAD

**Issue by pascalfree** [juntagrico/juntagrico#589]
Besides others (#495) the weekday on the depots is currently used to group the depots by day on the "depot overview list".
The sums there can be used as a packing/delivery list, for the cases where only one delivery is done per day. This last assumption is not true for at least one user, who does 2 Tours on the same day.
This is also not correct for the other existing case, where each depot has its own tour. But there the "depot overview list" is not relevant and the "depot lists" can be used directly to see the sums. 

# Suggestion
- create a foreign key on `depot` to a new entity `tour`, that specifies the details of each tour (name, weekday, description).
- create a "delivery list" that lists all tours and each depot on the tour and the sum of the products for each tour.
- question the use of the "depot overview list" and remove it if not needed anymore.
- ~~remove the weekday entry on `depot`, i.e. migrate it to a tour~~ Use the field for #495, and migrate the weekday name to the name of the tour.
- Consider if the `tour` may be nullable, i.e. a depot without delivery? Maybe for some alternative distribution concept.

# Assumptions
- Each selectable depot only gets one delivery. Even if the same physical location gets delivered twice, it is safe to assume that 2 depot instances are created for it, such that the members can select which day they want to pick up.
- All products are delivered on the same tour. I know cases, where some products are picked up in a central depot at any time, so additional columns on the "delivery list" may just be ignored. If there is a case where some products are delivered on different days to the same or another depot more generalization would be needed. Let's hope nobody does that.

**Comment by nixnuex** [comment]
*thumbs up*

This is exactly what we'll need in a couple of weeks from now (two delivery tours on same day). Proposal looks legit.

**Comment by pascalfree** [comment]
# Delivieries

There is a hidden relation between the depot weekday and the delivery:
https://github.com/juntagrico/juntagrico/blob/83b4d166a353c8670052696a8e8d7bbcfcb963dd/juntagrico/dao/deliverydao.py#L20-L22

The current relation says, that all subscription sizes delivered on the same day contain the same items. With the suggestion here, this may become "same tour" instead of "same day". The truth is more complicated than either: The items may or may not depend on a variety of factors.
In our case sometimes all depots get the same items and sometimes it is different. (This is due to the number of harvested vegetables. Over multiple weeks this is equalized). The delivery feature would need extension to cover all relevant use cases. A user study should identify which are the relevant use cases.
In theory the deliveries are related to each individual subscription part, i.e., if a coherent list of relevant deliveries shall be shown to a member (that they actually should have received), each subscription part has multiple deliveries over their lifetime. This should also exclude vacations #511.

**For the sake of this issue, the same transition from weekdays to tours shall apply here.** That means the delivery gets an optional foreign key to the tour. Optional, because before it was also possible to create a delivery for a day that had no matching weekday on a depot and these couldn't be migrated otherwise. Such a delivery was never shown and shall behave the same here. Changing the tour for a depot will have an impact, i.e. previous deliveries to that depot will lose the link to the depot (as they do with the current solution if the delivery day changes).

# Weekdays

The weekday is actually not required on the Tour. The tour may be named like a weekday and sorted accordingly, but there is no relation (besides the above of the delivery), that needs to know about a weekday for the tour.
So i suggest to not migrate the "weekday" field.
Instead it shall stay for it's other purpose (which will become it's unique purpose) to describe the pickup weekday (#495):
https://github.com/juntagrico/juntagrico/blob/5c30a432573bcf5bd0062c008e54f19df208d6ae/juntagrico/templates/createsubscription/summary.html#L62


# Todo

- [ ] Extend the delivery feature (new issue)
