### ISSUE TITLE
do not display unvisible extra sub stuff on depot list

### ISSUE THREAD

**Issue by motu55** [juntagrico/juntagrico#6]

**Comment by motu55** [comment]
take into account the following lines of code when generating depot lists
https://github.com/juntagrico/juntagrico/blob/master/juntagrico/entity/extrasubs.py#L20
https://github.com/juntagrico/juntagrico/blob/master/juntagrico/entity/extrasubs.py#L41

**Comment by nixnuex** [comment]
What exactly is meant by this? Is it related to https://github.com/juntagrico/juntagrico/pull/153?
