### ISSUE TITLE
Dates and Timezones

### ISSUE THREAD

**Issue by pascalfree** [juntagrico/juntagrico#608]
Timezones are always fun.

# Issues (selection)

* When setting the cancellation date of a subscription part to today at 00:30 in the morning (in Zurich) the warning will appear, that the date can not be in the future (because UTC is 23:30 of the previous day).

# Solution

* Never use `timezone.now().date()`
* To get the current date always use `datetime.date.today()`
* To get the current datetime always use `timezone.now()`
* Check for rare cases where the above is not true.
    1. `FutureDateTimeFilter` should use [this](https://stackoverflow.com/questions/37735191/how-do-i-extend-django-admins-datefieldlistfilter-class).

# Why?

As the [django documentation](https://docs.djangoproject.com/en/4.1/topics/i18n/timezones/#troubleshooting) puts it:
"A datetime represents a point in time. It’s absolute: it doesn’t depend on anything. On the contrary, a date is a calendaring concept. It’s a period of time whose bounds **depend on the time zone in which the date is considered**"

## Datetimes

If USE_TZ is True, django stores all datetimes in UTC (and only converts them for display to the user and from user input). `timezone.now()` actually returns a datetime in UTC, which is good, because it is then used to compare with datetimes from the database which are stored in UTC as well. 

## Dates
Dates on the other hand are only meaningful together with a timezone. E.g. if my CSA is in Zurich and I'm in central america and for some reason I want to look at all active subscriptions, I would want to get all subscriptions with an activation date <= today and deactivation date > today. But what do I expect if in Zurich the next day already started? Whose midnight is relevant for the activation and deactivation of the subscription? That is an active decision that has to be made and normally it makes sense to use the Timezone where the CSA is located for that.
**Once we have decided on a timezone, we must use it consistently when dealing with dates.**
The `TIME_ZONE` setting will do the trick here. `datetime.date.today()` will take the setting into account. That's also how django handles it: For `DateFields` that use `auto_now_add` it uses that method.
https://github.com/django/django/blob/ba1654cb54eccef3ba29e455cd5065aed84e1f90/django/db/models/fields/__init__.py#L1407

Currently `timezone.now().date()` is used in many places, which is equivalent to using UTC as the reference timezone. That one is close to our users time zones, which is why this has only affected people working after midnight. ;-)

**Comment by pascalfree** [comment]
The fix requires some migration steps by the users, when the TIME_ZONE has not been specified in the settings.py before. So this fix is moved to 1.6

**Comment by patrickuhlmann** [comment]
I think we once had a bug with the depot list. It is generated each day at 23:45. We disabled a (half) part on the 30.04 and activated a (full) part on the 01.05. The list that was generated at 30.04 23:45 had neither the old nor the new part listed. I was wondering if that might also be related to the timezone
