### ISSUE TITLE
Entries under "Nächste Einsätze" not sorted by date

### ISSUE THREAD

**Issue by zuckerruebe** [juntagrico/juntagrico#610]
As a user, I'd like the entries under "Nächste Einsätze" to be sorted chronologically, to make it easier to get an overview of the events that I've subscribed to. See here:

![image](https://user-images.githubusercontent.com/11159050/224575006-ec576cb6-5373-4bfa-b973-9a940978106c.png)

**Comment by zuckerruebe** [comment]
Is there a deadline for the 1.6.0 release? I could try to fix this issue if you could give me a hint to get started. Just glancing at the code, I couldn't see why the events aren't sorted.

**Comment by pascalfree** [comment]
There is no deadline for 1.6. Goal is to close the now open PRs on it an release. But that probably still takes a month.

To fix this issue a order_by('time') is needed here
https://github.com/juntagrico/juntagrico/blob/main/juntagrico/dao/jobdao.py#L79-L80
