### ISSUE TITLE
Leaflet maps marker breaks on high resolution screens when using ManifestStaticFileStorage

### ISSUE THREAD

**Issue by pascalfree** [juntagrico/juntagrico#618]
When using ManifestStaticFileStorage (which is encouraged), Leaflet code that replaces the marker image in javascript fails, as the file name is modified.
This issue is known and some workarounds are suggested.
https://github.com/Leaflet/Leaflet/issues/4968
Leaflet will not fix this.

**Comment by patrickuhlmann** [comment]
Where are these markers displayed?

**Comment by pascalfree** [comment]
They are shown during the signup process in the depot selection. If the coordinates of the depot locations are configured.
