### ISSUE TITLE
amend display of contact in job reminder email

### ISSUE THREAD

**Issue by flurin-conradin** [juntagrico/juntagrico#619]
There seems to be a small issue in the job reminder email, i.e. the contact is displayed as a "Polimorphic queryset". The intention was probably to display a name and an email address.

![image](https://user-images.githubusercontent.com/32741304/230789128-2d236fac-786a-42fe-9f54-76d8ba381995.png)

**Comment by pascalfree** [comment]
Did you override this email template? You might have to update it.

**Comment by flurin-conradin** [comment]
I was indeed working on customizing the text, however, I reproduced this without a custom template. Is it displayed correctly in your case if you run `python manage.py mailtexts`?

**Comment by pascalfree** [comment]
Yes that looks correct in my case, but I only have 1 contact.
I'll have to test it with multiple contacts like in your case.

**Comment by flurin-conradin** [comment]
I might have the time to look into this in the next weeks. Would you want me to have another look at it?

**Comment by pascalfree** [comment]
Sorry for the late reply.
Feel free to look for the bug in the code.
I assume the template just needs a `|join:", "` filter where the contact is printed.

**Comment by flurin-conradin** [comment]
No worries @pascalfree ! 
I did have a look into this. The `|join` is already implemented, but it fails silently.
![image](https://github.com/juntagrico/juntagrico/assets/32741304/d4a62afa-aa0d-4aa2-9958-8af697659828)

It seems that this is due to the fact that `autoescape` is turned off in `./templates/mails/email.txt` and thus line 591 above is not executed. 

One solution would be to turn autoescape back on just for the contacts in the email. As an illustration, I created two emails, one with `autoescape=on` and the other one with `autoescape=off`

`off`
![image](https://github.com/juntagrico/juntagrico/assets/32741304/93d10779-3779-4d13-8857-2a74e4a28551)

`on`
![image](https://github.com/juntagrico/juntagrico/assets/32741304/68f294e2-a078-48ad-8192-938898cdfa41)

I don't think I can contribute anything though as I do not have the rights to create a branch on juntagrico.

**Comment by pascalfree** [comment]
Sorry for the late reply.
The autoescape is turned off, as it assumes HTML output and would escape things like apostrophes or special characters in names. see #590
It seems that join with autoescape has the side effect that we were taking advantage of before.

As we need autoescape off I would fix this here by replacing the join with a for loop in the template.

I now added you to the team, so you can create PRs directly.

best

**Comment by flurin-conradin** [comment]
No worries @pascalfree ! I will have a look now. Thanks for adding me to the team.

**Comment by flurin-conradin** [comment]
@pascalfree I created a [PR](https://github.com/juntagrico/juntagrico/pull/649) for this. https://github.com/juntagrico/juntagrico/pull/649 Happy to amend anything if you see any need.
