### ISSUE TITLE
Cancellation month not taken into account when calculating next size change date

### ISSUE THREAD

**Issue by kahrpatrick** [juntagrico/juntagrico#622]
Currently 'next_size_change_date' is equal to the start of the next business year. 

https://github.com/juntagrico/juntagrico/blob/9096a0bd6cfdc51324834e68bd83e52d5d680337/juntagrico/entity/subs.py#L248

This does not take into account the next cancellation date. Users can therefore request a size change after the cancellation date for the upcoming business year and be told that it will be activated in the upcoming business year. This does not correspond to the text in https://github.com/juntagrico/juntagrico/blob/9096a0bd6cfdc51324834e68bd83e52d5d680337/juntagrico/templates/snippets/snippet_subscription_change_size.html#L11

If I understand this correctly, 'next_size_change_date' should add a year if the cancellation date for the upcoming business year is already over.

Example:

BUSINESS_YEAR_START={'day':1, 'month':6}
BUSINESS_YEAR_CANCELATION_MONTH=1

On the 2.5.23 the view will show: "Nächstmögliches Datum:
01.06.2023" instead of 01.06.2024

**Comment by pascalfree** [comment]
Yes this is part of the fix.

The issue goes further: Parts may be already activated with a future date. In that case the actual date of change shall be shown. But the change my be different for each part, which can't be displayed in the current way.

For 1.6 the partial fix shall be implemented.

**Comment by patrickuhlmann** [comment]
We had such a case at Gartenberg and discussed how to handle. We do have full and half baskets. We came to the following conclusion:

- if the change is from half to full it can be activated right away (it is like booking another half basket)
- if the change is from full to half it will be done at the end of the business year (it is like cancelling half of the basket)

Maybe I'll try to customize the text in the email accordingly in our repo.

**Comment by pascalfree** [comment]
This is solved with the new subscription overview in 1.6.0. For previous versions I don't see a suitable easy fix and would suggest to remove the date.
I'll close this issue with respect to 1.6.0
