### ISSUE TITLE
Show booked out jobs on home page

### ISSUE THREAD

**Issue by kahrpatrick** [juntagrico/juntagrico#625]
Currently the home page only lists upcoming jobs that are not fully booked. 
Since the title (in German) is "Aktuelle Arbeitseinsätze", this can be confusing as it is not clear that there are other upcoming jobs that are fully booked. 
Maybe one could change the title to clarify that these are only jobs with free slots, or list upcoming jobs that are booked out in a separate block underneath?

**Comment by pascalfree** [comment]
Thanks for opening the issue.

I would go for the option to change the title, e.g. to "Offene Arbeitseinsätze", to not clutter the home page with booked out jobs.
