### ISSUE TITLE
ics event sent in email confirmations has no title

### ISSUE THREAD

**Issue by nikmess** [juntagrico/juntagrico#657]
The `.ics` files sent in email confirmations have the wrong field name `NAME` for the `VEVENT` title. The event therefore has no title when imported into e.g. Google Calendar or Outlook.

**Comment by nikmess** [comment]
Pull request for fix: https://github.com/juntagrico/juntagrico/pull/658

**Comment by pascalfree** [comment]
Hi @nikmess 
Thank you for your contribution.

This has been fixed upstream for the upcoming 1.6 release already https://github.com/juntagrico/juntagrico/pull/640
But I agree that it is a bug and should be fixed for 1.5 as well.
