### ISSUE TITLE
Email `FROM_FILTER` is not working

### ISSUE THREAD

**Issue by leorott** [juntagrico/juntagrico#716]
### Issue
In our `settings.py`, we have defined the following `FROM_FILTER` configuration:

```python
FROM_FILTER = {
    'filter_expression': '[A-Za-z0-9._%+-]+@puraverdura\.ch',
    'replacement_from': 'asdf@puraverdura.ch'
}
```
(`replacement_from` changed to prevent spam)

However, when using email addresses with domains other than @puraverdura.ch (e.g., @gmail.com, @yahoo.com), the filter does not replace these email addresses as expected.

We use Juntagrico `1.5.8`

**Comment by leorott** [comment]
I just checked with the `django admin shell` and seems that the value set in the `settings.py` is ignored. Could it be because the `filter_expression` and `replacement_from` are hardcoded in the `config.py`?

https://github.com/juntagrico/juntagrico/blob/21258875cd3fe3268d75b9c4d2451e460ba2e789/juntagrico/config.py#L144-L149

**Comment by pascalfree** [comment]
Hi @leorott 

The value in the config.py is just the default value. Your setting should override it correctly.
I tried your settings locally with juntagrico 1.5.8 and they work as expected.
Do you test send the emails with the form (/my/mails) or somewhere else? How did you test it in the admin shell?

**Comment by pascalfree** [comment]
I looked more into it. The redeployment button will not restart the docker container, when pip install of the requirements fail. This I think is the case with your requirements.txt as it tries to install juntagrico-badges 1.6 which is incompatible.
You should fix it to:

git+https://github.com/juntagrico/juntagrico-badges.git@1.5.0

I will open an issue on the paas to improve the visibility of a failed redeploy. 🙂

**Comment by pascalfree** [comment]
Opened new issue: https://github.com/juntagrico/juntagrico-paas/issues/13
Closing here.

**Comment by leorott** [comment]
I fixed it. Thank you very much for your help and sorry for the late reply.
