### ISSUE TITLE
Subscription parts cannot be cancelled

### ISSUE THREAD

**Issue by nixnuex** [juntagrico/juntagrico#717]
The only option shown for each part is "Abo komplett kündigen". Probably some issue with the logic in `size_change.html` line 50?

<img width="398" alt="Bildschirmfoto 2024-09-26 um 22 11 22" src="https://github.com/user-attachments/assets/2b43ceb7-558a-4333-8850-39c08bf0ebff">

**Comment by pascalfree** [comment]
This is in the new template arround here:
https://github.com/juntagrico/juntagrico/blob/main/juntagrico%2Ftemplates%2Fjuntagrico%2Fmy%2Fsubscription%2Fsnippets%2Fpart_list.html#L51

Extra parts (Zusatzabos) are not yet considered in this code.
If it's an extra part only the cancel button should be shown in any case.
