### ISSUE TITLE
Admin erhält keine Benachrichtigung wenn Mitglieder künden

### ISSUE THREAD

**Issue by patrickuhlmann** [juntagrico/juntagrico#718]
Wir haben bei uns den Mitgliedern der Koordinationsgruppe jeweils beim Benutzer "Mitarbeiter-Status" und "Administrator-Status" ausgewählt. Nun habe ich festgestellt, dass wir keine E-Mail-Benachrichtigung erhalten bei Mitgliedschaftskündigungen. Bei einer Abokündigung aber schon.

Gemäss Beschreibung sollte der Administrator alle Berechtigungen haben, ohne diese einzeln zuweisen zu müssen. Ist es möglich das dort die Berechtigung "juntagrico | Mitglied | Wird bei Mitglied Kündigung informiert" fehlt?

Wenn ich diese manuell zuweise erhalten wir die Mails.

**Comment by patrickuhlmann** [comment]
Ah ok. Wichtiger als in der Doku fände ich es vorallem im Beschreibungstext des Feldes damit man sich das bewusst ist da die Benarchrichtigungen ja auch als Berechtigungen abgebildet sind. Aber ist es dann ein Bug das man über andere Änderungen benachrichtigt wird? (z. B. neue Mitglieder, neue Abos, Bestandteil gekündigt etc.)

**Comment by pascalfree** [comment]
Es gehen gar keine Benachrichtigungen raus nur mit dem admin status. Hast du den admin noch in einer Gruppe mit der Berechtigung?

Der Text dort kommt von der existierenden django auth app. Müsste schauen, wie das angepasst werden kann.

**Comment by patrickuhlmann** [comment]
Nein ich hatte nur Admin und Mitarbeiter. Vielleicht wurden die Mails wegen dem Mitarbeiterstatus versendet?

**Comment by patrickuhlmann** [comment]
Habe es nochmal geprüft. Bekomme effektiv keine Mails mit Admin und MItarbeiterstatus. Vermutlich war da effektiv noch eine andere Gruppe im Spiel. Tut mir leid für die Umstände. Habe nun allen Admin und MItarbeiter gegeben und eine Benachrichtigungsgruppe angelegt mit allen "informiert" Berechtigungen und diese noch zugewiesen.

**Comment by pascalfree** [comment]
Ich habe die Doku nun mit einem disclaimer ergänzt:
https://juntagrico.readthedocs.io/en/latest/reference/permissions.html#notifications
