### ISSUE TITLE
Custom Permissions for moderators

### ISSUE THREAD

**Issue by pascalfree** [juntagrico/juntagrico#90]
These custom permission would help simplifying the django admin for moderators and prevent accidental changes.
I collect all suggestions here to better identify possible overlaps

# can_change_past_job
As discussed in #80.
Required to change anything about a past job.
Would allow to give moderators the right to only change future jobs.

# can_change_inactive_subscription
As discussed in #86.
Required to change anything about an inactive subscription. Maybe some fields, like the `notes`, might still be mutable without this permission.

**Comment by motu55** [comment]
same procedure for incative subscription as the solution for #80
